In [20]:
# python notebook for Make Your Own Neural Network
# code for a 3-layer neural network, and code for learning the MNIST dataset
# (c) Tariq Rashid, 2016
# license is GPLv2

In [21]:
import numpy
# scipy.special for the sigmoid function expit()
import scipy.special
# library for plotting arrays
import matplotlib.pyplot
# ensure the plots are inside this notebook, not an external window
%matplotlib inline

In [22]:
# neural network class definition
class neuralNetwork:
    
    
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc 
        self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        #self.wih = numpy.random.normal(0.0, 0.5, (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        #self.who = numpy.random.normal(0.0, 0.5, (self.hnodes, self.inodes))
        print("wih: ", self.wih)
        print("who: ", self.who)

        # learning rate
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass

    
    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        print("INPUTS")
        print(inputs)
        print("===========================")
        targets = numpy.array(targets_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        print("HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)")
        print(hidden_inputs)
        print("===========================")
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        print("HIDDEN OUTPUTS (después de aplicar la función sigmoide)")
        print(hidden_outputs)
        print("===========================")
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        print("FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)")
        print(final_inputs)
        print("===========================")
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        print("FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)")
        print(final_outputs)
        print("===========================")
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        print("ERROR (target - valor de los final outputs)")
        print(output_errors)
        print("===========================")
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        
        # update the weights for the links between the hidden and output layers
        print("Peso actualizado del output layer: ", self.who)
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        print("Peso actualizado del hidden layer: ", self.wih)
        
        print("============= FINAL DE FASE DE ENTRENAMIENTO ==============")
        
        pass

    
    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs

In [23]:
# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# learning rate
learning_rate = 0.1

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)

wih:  [[ 1.14141141 -0.16091703 -0.21066219]
 [ 0.34570386 -0.50197504 -0.76776826]
 [ 0.45400492 -0.63124494 -0.0612365 ]]
who:  [[-0.79266863  0.69793782 -0.69002279]
 [ 1.2414637   0.1591999  -0.72928726]
 [ 0.07503579  0.65811911  0.70649624]]


In [24]:
# load the mnist training data CSV file into a list
training_data_file = open("mnist_dataset/contador.csv", 'r')
training_data_list = training_data_file.readlines()
training_data_file.close()

In [25]:
# load the mnist test data CSV file into a list
test_data_file = open("mnist_dataset/contador.csv", 'r')
test_data_list = test_data_file.readlines()
test_data_file.close()

In [31]:
# train the neural network

# epochs is the number of times the training data set is used for training
epochs = 100

for e in range(epochs):
    # go through all records in the training data set
    contador = 1
    for record in training_data_list:
        print("Iteración #", e)
        # split the record by the ',' commas
        all_values = record.split(',')
        # scale and shift the inputs
        inputs = (numpy.asfarray(all_values[0:3]) / 1.0) + 0.00
        # inputs = (numpy.asfarray(all_values[0:3]) / 255.0 * 0.99) + 0.01
        # create the target output values (all 0.01, except the desired label which is 0.99)
        # targets = numpy.zeros(output_nodes) + 0.01
        target_values = training_data_list[contador].split(',')
        targets = (numpy.asfarray(target_values[0:3]) / 1.0) + 0.00
        print("inputs -> ", inputs)
        print("targets -> ", targets)
        # all_values[0] is the target label for this record
        # targets[int(all_values[0])] = 0.99
        n.train(inputs, targets)
        contador += 1
        if(contador == 8):
            contador = 0
        pass
    pass

Iteración # 0
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.2204458 ]
 [ 0.20875223]
 [ 0.60981967]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44511065]
 [ 0.55199936]
 [ 0.64789967]]
ERROR (target - valor de los final outputs)
[[-0.44511065]
 [-0.55199936]
 [ 0.35210033]]
Peso actualizado del output layer:  [[-0.63942945  0.79153979 -0.59300195]
 [ 1.13921314  0.08284051 -0.8045492 ]
 [-0.04183664  0.64304896  0.61842702]]
Peso actualizado del hidden layer:  [[ 0.80433151 -0.32413786 -0.38132968]
 [ 0.52644112 -0.48863392 -1.04133773]
 [ 0.20912129 -0.68426032 -0.46084862]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 0
inputs ->  [ 0.  0.  1.]
targets -

targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.77675121]
 [ 0.5449704 ]
 [ 0.18875718]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.6849795 ]
 [ 0.6329679 ]
 [ 0.54704968]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.26417104]
 [ 0.37603993]
 [ 0.70764392]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.43433865]
 [ 0.59291763]
 [ 0.66988034]]
ERROR (target - valor de los final outputs)
[[ 0.56566135]
 [-0.59291763]
 [ 0.33011966]]
Peso actualizado del output layer:  [[-0.63830369  0.78935039 -0.59698337]
 [ 1.12914658  0.07427178 -0.81238322]
 [-0.05263739  0.64564748  0.61242211]]
Peso actualizado del hidden layer:  [[ 0.75413867 -0.33704184 -0.391787  ]
 [ 0.55927219 -0.48909826 -1.08039014]
 [ 0.19733451 -0.6881969  -0.5113628 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 1
inputs ->  [ 1.  0.  1.]
tar

 [-0.05548985  0.65189284  0.61270413]]
Peso actualizado del hidden layer:  [[ 0.73110305 -0.34639162 -0.39562352]
 [ 0.57985752 -0.48843108 -1.10438544]
 [ 0.15220423 -0.69119362 -0.57074459]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 2
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.38471143]
 [ 0.09142644]
 [-0.53898938]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.59500894]
 [ 0.5228407 ]
 [ 0.36842271]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15216237]
 [ 0.39524097]
 [ 0.52351054]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46203264]
 [ 0.59754372]
 [ 0.62796828]]
ERROR (target - valor de los final outputs)
[[ 0.53796736]
 [ 0.40245628]
 [ 0.37203172]]
Peso actualizado del output layer:  [[-0.61042454  0.81108286 -0.57819848]
 [ 1.11788292  0.06266706 -0.82154069]
 [-

[[ 0.35073454]
 [ 0.11038454]
 [-0.56056319]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.58679569]
 [ 0.52756815]
 [ 0.36341716]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12919092]
 [ 0.38105718]
 [ 0.51971396]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46774712]
 [ 0.59412806]
 [ 0.62708088]]
ERROR (target - valor de los final outputs)
[[ 0.53225288]
 [ 0.40587194]
 [ 0.37291912]]
Peso actualizado del output layer:  [[-0.60096607  0.81857406 -0.57344627]
 [ 1.11074088  0.05650568 -0.8269598 ]
 [-0.07131697  0.64851092  0.60379304]]
Peso actualizado del hidden layer:  [[ 0.7082968  -0.35250165 -0.40165991]
 [ 0.61575393 -0.47045263 -1.13039061]
 [ 0.12393549 -0.70373235 -0.60354703]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 3
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-

HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.0831803 ]
 [-0.9924198 ]
 [-1.23643044]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.47921691]
 [ 0.27043439]
 [ 0.22505793]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.18186633]
 [ 0.36031362]
 [ 0.27818064]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45465832]
 [ 0.58911635]
 [ 0.56910013]]
ERROR (target - valor de los final outputs)
[[-0.45465832]
 [-0.58911635]
 [-0.56910013]]
Peso actualizado del output layer:  [[-0.58444851  0.83288293 -0.5644276 ]
 [ 1.10958867  0.05575583 -0.82866811]
 [-0.0733193   0.65550976  0.60448484]]
Peso actualizado del hidden layer:  [[ 0.6752994  -0.36896126 -0.41544055]
 [ 0.61857567 -0.48562188 -1.17181246]
 [ 0.11284778 -0.6995611  -0.6287469 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 5
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HID

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15384756]
 [ 0.15276809]
 [ 0.58362687]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46161379]
 [ 0.53811792]
 [ 0.64190152]]
ERROR (target - valor de los final outputs)
[[-0.46161379]
 [-0.53811792]
 [ 0.35809848]]
Peso actualizado del output layer:  [[-0.58157082  0.83697596 -0.56310026]
 [ 1.09624276  0.04615356 -0.83686015]
 [-0.08671267  0.65448019  0.59948622]]
Peso actualizado del hidden layer:  [[ 0.65192618 -0.37595902 -0.41952361]
 [ 0.63677725 -0.48547517 -1.19770844]
 [ 0.09512925 -0.70249177 -0.66048236]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 6
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.41952361]
 [-1.19770844]
 [-0.66048236]]
HIDDEN OUTPUTS (después 

ERROR (target - valor de los final outputs)
[[ 0.53222577]
 [-0.57374736]
 [ 0.33559181]]
Peso actualizado del output layer:  [[-0.58438746  0.83325427 -0.57029595]
 [ 1.08812516  0.03874587 -0.84347693]
 [-0.0950568   0.6600391   0.59799156]]
Peso actualizado del hidden layer:  [[ 0.60732756 -0.38346624 -0.42227105]
 [ 0.66933909 -0.4873689  -1.23567141]
 [ 0.08738367 -0.70557614 -0.70540143]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 7
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.18505651]
 [-0.56633232]
 [-0.61801777]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.54613255]
 [ 0.36208355]
 [ 0.35023241]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.20689288]
 [ 0.30198161]
 [ 0.40232185]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44846049]
 [ 0.57492687]
 [ 0.59924538]]
ERR

 [-0.0964062   0.66847128  0.60106577]]
Peso actualizado del hidden layer:  [[ 0.59049679 -0.38925704 -0.41955786]
 [ 0.68909259 -0.48762462 -1.25962031]
 [ 0.04757911 -0.70848142 -0.75891719]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 8
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.20123975]
 [ 0.20146797]
 [-0.66090232]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.55014084]
 [ 0.55019732]
 [ 0.34053695]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.02841653]
 [ 0.31861937]
 [ 0.51066303]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49289635]
 [ 0.57898775]
 [ 0.62496189]]
ERROR (target - valor de los final outputs)
[[ 0.50710365]
 [ 0.42101225]
 [ 0.37503811]]
Peso actualizado del output layer:  [[-0.56128999  0.85363606 -0.55587582]
 [ 1.07866286  0.02779037 -0.85185265]
 [-

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5344218 ]
 [ 0.35851337]
 [ 0.32930693]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.17735513]
 [ 0.29390396]
 [ 0.38404987]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45577708]
 [ 0.57295162]
 [ 0.59484951]]
ERROR (target - valor de los final outputs)
[[ 0.54422292]
 [ 0.42704838]
 [-0.59484951]]
Peso actualizado del output layer:  [[-0.56192111  0.85538932 -0.55790122]
 [ 1.06728654  0.01868232 -0.85991235]
 [-0.10246054  0.67224822  0.60064647]]
Peso actualizado del hidden layer:  [[ 0.56944841 -0.39459595 -0.42104698]
 [ 0.70691075 -0.48803628 -1.28534716]
 [ 0.03169613 -0.71143079 -0.78843335]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 9
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.17485246]
 [ 0.21887446]
 [-0.67973466]]
HID

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45910415]
 [ 0.57209625]
 [ 0.59284164]]
ERROR (target - valor de los final outputs)
[[ 0.54089585]
 [ 0.42790375]
 [-0.59284164]]
Peso actualizado del output layer:  [[-0.55562961  0.86190877 -0.55564793]
 [ 1.06171603  0.01344626 -0.86433795]
 [-0.10836029  0.67628331  0.60059881]]
Peso actualizado del hidden layer:  [[ 0.54898591 -0.39951585 -0.42194136]
 [ 0.72460049 -0.48860232 -1.31104241]
 [ 0.01620936 -0.71443396 -0.8174777 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 10
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.14947006]
 [ 0.23599817]
 [-0.6982246 ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5372981 ]
 [ 0.55872723]
 [ 0.33220597]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.00636355]
 [ 0.2970091 ]
 [ 0.51072092]]
FI

INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.07608306]
 [-0.60576077]
 [-0.84478087]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.51901159]
 [ 0.35302683]
 [ 0.30052883]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.13959216]
 [ 0.28434349]
 [ 0.36046899]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46515852]
 [ 0.57061076]
 [ 0.58915396]]
ERROR (target - valor de los final outputs)
[[ 0.53484148]
 [ 0.42938924]
 [-0.58915396]]
Peso actualizado del output layer:  [[-0.54418923  0.87460676 -0.55206448]
 [ 1.05106752  0.00331099 -0.87293324]
 [-0.11977421  0.68508644  0.6015373 ]]
Peso actualizado del hidden layer:  [[ 0.50969523 -0.40821819 -0.42208748]
 [ 0.759579   -0.4901884  -1.36234426]
 [-0.01363459 -0.72063121 -0.87421827]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 12
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
IN

HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.07875525]
 [ 0.28565924]
 [-0.75185491]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.51967864]
 [ 0.57093311]
 [ 0.32041726]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.05374746]
 [ 0.26753031]
 [ 0.51377794]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.51343363]
 [ 0.5664865 ]
 [ 0.62569169]]
ERROR (target - valor de los final outputs)
[[ 0.48656637]
 [ 0.4335135 ]
 [ 0.37430831]]
Peso actualizado del output layer:  [[-0.5321904   0.88545025 -0.54684141]
 [ 1.05139309  0.00210583 -0.87404313]
 [-0.13264727  0.68483551  0.59833425]]
Peso actualizado del hidden layer:  [[ 0.49448437 -0.40838072 -0.42140214]
 [ 0.79371778 -0.47434682 -1.38795233]
 [-0.03718667 -0.73300378 -0.90194508]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 13
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HI

 [-0.13078996  0.69480261  0.60373014]]
Peso actualizado del hidden layer:  [[ 0.47239703 -0.41558157 -0.42024838]
 [ 0.79400455 -0.49235994 -1.41353188]
 [-0.04206142 -0.72711652 -0.92926151]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 14
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.05681546]
 [ 0.30164461]
 [-0.76917794]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.51420005]
 [ 0.57484451]
 [ 0.31665696]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.06841396]
 [ 0.25839854]
 [ 0.51547133]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.51709682]
 [ 0.56424258]
 [ 0.6260882 ]]
ERROR (target - valor de los final outputs)
[[ 0.48290318]
 [ 0.43575742]
 [ 0.3739118 ]]
Peso actualizado del output layer:  [[-0.52742767  0.89150039 -0.54588034]
 [ 1.04640073 -0.00271135 -0.87824427]
 [

Peso actualizado del output layer:  [[-0.5168915   0.90438345 -0.54142532]
 [ 1.04702901 -0.00119166 -0.87900664]
 [-0.1389197   0.70010726  0.604091  ]]
Peso actualizado del hidden layer:  [[ 0.45162254 -0.4216297  -0.42525586]
 [ 0.81221604 -0.49244593 -1.45461009]
 [-0.05944966 -0.73415093 -0.95075694]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 16
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.0818425 ]
 [ 0.07776148]
 [ 0.57713941]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47955079]
 [ 0.51943058]
 [ 0.64040892]]
ERROR (target - valor de los final outputs)
[[-0.47955079]
 [-0.51943058]
 [ 0.35959108]]
Peso actualizado del output layer:  [[-0.521819

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.07663625]
 [ 0.07115256]
 [ 0.57821742]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48085031]
 [ 0.51778064]
 [ 0.64065713]]
ERROR (target - valor de los final outputs)
[[-0.48085031]
 [-0.51778064]
 [ 0.35934287]]
Peso actualizado del output layer:  [[-0.51774393  0.90721317 -0.54274174]
 [ 1.03662998 -0.00924117 -0.8850837 ]
 [-0.14973785  0.70213743  0.60403527]]
Peso actualizado del hidden layer:  [[ 0.43428355 -0.42440068 -0.42308629]
 [ 0.82902156 -0.49393064 -1.48012608]
 [-0.0729514  -0.7376974  -0.97743149]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 17
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.42308629]
 [-1.48012608]
 [-0.97743149]]
HIDDEN OUTPUTS (después

 [-0.15628588  0.70943107  0.60666369]]
Peso actualizado del hidden layer:  [[ 0.41733841 -0.41067889 -0.40159603]
 [ 0.84568727 -0.49947534 -1.51775657]
 [-0.08614283 -0.73931757 -1.01361189]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 18
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.81227491]
 [-2.01723192]
 [-1.75292946]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.30740594]
 [ 0.11740552]
 [ 0.14767809]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.13902429]
 [ 0.18527181]
 [ 0.12689295]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4652998 ]
 [ 0.54618591]
 [ 0.53168074]]
ERROR (target - valor de los final outputs)
[[ 0.5347002 ]
 [-0.54618591]
 [-0.53168074]]
Peso actualizado del output layer:  [[-0.52925005  0.90032651 -0.55548518]
 [ 1.03478501 -0.01358299 -0.88863916]
 [

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46560338]
 [ 0.54643191]
 [ 0.53048052]]
ERROR (target - valor de los final outputs)
[[ 0.53439662]
 [-0.54643191]
 [-0.53048052]]
Peso actualizado del output layer:  [[-0.52576254  0.90607255 -0.55542911]
 [ 1.03035657 -0.01793517 -0.89260031]
 [-0.1576962   0.71896629  0.61224818]]
Peso actualizado del hidden layer:  [[ 0.40076814 -0.42929196 -0.4148591 ]
 [ 0.86221338 -0.50014872 -1.54196806]
 [-0.09903344 -0.74470368 -1.04110484]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 19
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.40076814]
 [ 0.86221338]
 [-0.09903344]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5988722 ]
 [ 0.70312289]
 [ 0.47526185]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.0626718 ]
 [ 0.17571004]
 [ 0.69765767]]
FI

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.13681167]
 [ 0.18738299]
 [ 0.11733979]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46585033]
 [ 0.54670915]
 [ 0.52930134]]
ERROR (target - valor de los final outputs)
[[ 0.53414967]
 [-0.54670915]
 [-0.52930134]]
Peso actualizado del output layer:  [[-0.52253471  0.91175071 -0.55557849]
 [ 1.02603519 -0.02220036 -0.89651682]
 [-0.16289314  0.72503419  0.61493987]]
Peso actualizado del hidden layer:  [[ 0.38455501 -0.43137482 -0.41143288]
 [ 0.87860043 -0.50207554 -1.5672792 ]
 [-0.11163232 -0.74845733 -1.06653611]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 20
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.38455501]
 [ 0.87860043]
 [-0.11163232]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.59497124]
 [ 0.70653211]
 [ 0.47212087]]
FI

targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.36868246]
 [ 0.89484926]
 [-0.12394816]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.59114058]
 [ 0.70988987]
 [ 0.46905257]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.08764381]
 [ 0.15858824]
 [ 0.70529136]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.52189694]
 [ 0.53956417]
 [ 0.66935989]]
ERROR (target - valor de los final outputs)
[[ 0.47810306]
 [-0.53956417]
 [ 0.33064011]]
Peso actualizado del output layer:  [[-0.51546172  0.91881599 -0.55410423]
 [ 1.01763994 -0.02786081 -0.90224837]
 [-0.17214204  0.72983339  0.61602941]]
Peso actualizado del hidden layer:  [[ 0.34807948 -0.43327389 -0.40766346]
 [ 0.90917557 -0.50411418 -1.59255119]
 [-0.11334927 -0.75228684 -1.09162447]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 21
inputs ->  [ 1.  0.  1.]
ta

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.48226924]
 [ 0.33347249]
 [ 0.22413552]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.05593824]
 [ 0.26670451]
 [ 0.30333345]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48601908]
 [ 0.56628369]
 [ 0.5752572 ]]
ERROR (target - valor de los final outputs)
[[ 0.51398092]
 [ 0.43371631]
 [-0.5752572 ]]
Peso actualizado del output layer:  [[-0.50575553  0.93278557 -0.54915986]
 [ 1.00566147 -0.04145297 -0.91226801]
 [-0.17306011  0.74146595  0.62255425]]
Peso actualizado del hidden layer:  [[ 0.33949637 -0.43500243 -0.39667763]
 [ 0.92603688 -0.50625966 -1.61700555]
 [-0.14336555 -0.75619014 -1.13439507]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 22
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.09550606]
 [ 0.41977722]
 [-0.8995557 ]]
HI

[[-0.05028558]
 [ 0.2657412 ]
 [ 0.29877552]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48743125]
 [ 0.56604708]
 [ 0.57414316]]
ERROR (target - valor de los final outputs)
[[ 0.51256875]
 [ 0.43395292]
 [-0.57414316]]
Peso actualizado del output layer:  [[-0.50332534  0.93823096 -0.54998647]
 [ 1.00169723 -0.04544836 -0.91596743]
 [-0.17831985  0.7480569   0.62582367]]
Peso actualizado del hidden layer:  [[ 0.32441555 -0.43657274 -0.39217853]
 [ 0.94191061 -0.50850693 -1.64226617]
 [-0.15478697 -0.76016489 -1.15850746]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 23
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.11215719]
 [ 0.43340368]
 [-0.91495186]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.47199006]
 [ 0.60668614]
 [ 0.2859876 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[

Peso actualizado del hidden layer:  [[ 0.30962568 -0.43799631 -0.38737412]
 [ 0.95764862 -0.51085092 -1.66748023]
 [-0.16595943 -0.76420848 -1.1823076 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 24
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.12837064]
 [ 0.44679771]
 [-0.93016791]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.46795134]
 [ 0.60987759]
 [ 0.28289065]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.19131682]
 [ 0.18183071]
 [ 0.54564028]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.54768385]
 [ 0.54533284]
 [ 0.63312351]]
ERROR (target - valor de los final outputs)
[[ 0.45231615]
 [ 0.45466716]
 [ 0.36687649]]
Peso actualizado del output layer:  [[-0.49501535  0.94783181 -0.54827355]
 [ 1.00290745 -0.04585174 -0.91737649]
 [-0.19029178  0.75017721  0.62628902]]
Pe

 [ 0.16977586]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49600073]
 [ 0.56728363]
 [ 0.54234231]]
ERROR (target - valor de los final outputs)
[[-0.49600073]
 [-0.56728363]
 [-0.54234231]]
Peso actualizado del output layer:  [[-0.48788523  0.95996293 -0.54639316]
 [ 1.00434162 -0.04277199 -0.91791067]
 [-0.19162422  0.76229647  0.6323439 ]]
Peso actualizado del hidden layer:  [[ 0.29392106 -0.44047728 -0.38750911]
 [ 0.97406543 -0.51247385 -1.70803602]
 [-0.18156222 -0.77299021 -1.20167038]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 26
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04154251]
 [ 0.01690503]
 [ 0.59674769]]
FINAL OUTPUTS (después de aplic

HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.38199429]
 [-1.73312375]
 [-1.22497926]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.40564599]
 [ 0.15018845]
 [ 0.22706138]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.18401987]
 [ 0.18183018]
 [ 0.18047032]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45412442]
 [ 0.54533271]
 [ 0.54499552]]
ERROR (target - valor de los final outputs)
[[-0.45412442]
 [ 0.45466729]
 [-0.54499552]]
Peso actualizado del output layer:  [[-0.49692212  0.95624194 -0.55518868]
 [ 0.98913313 -0.05596961 -0.92927171]
 [-0.19791462  0.77032605  0.63885596]]
Peso actualizado del hidden layer:  [[ 0.27980039 -0.44151548 -0.36311025]
 [ 0.98951462 -0.51501902 -1.74434929]
 [-0.19234397 -0.77724884 -1.23408019]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 27
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HI

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45401245]
 [ 0.54594675]
 [ 0.54362476]]
ERROR (target - valor de los final outputs)
[[-0.45401245]
 [ 0.45405325]
 [-0.54362476]]
Peso actualizado del output layer:  [[-0.49539836  0.96146675 -0.55673724]
 [ 0.98549866 -0.05956976 -0.93287822]
 [-0.20329424  0.77753415  0.64281856]]
Peso actualizado del hidden layer:  [[ 0.26593116 -0.44244204 -0.35730262]
 [ 1.00483694 -0.51764272 -1.76926871]
 [-0.20289479 -0.78156478 -1.25700906]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 28
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.44244204]
 [-0.51764272]
 [-0.78156478]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.39115923]
 [ 0.37340361]
 [ 0.31398274]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01276829]
 [ 0.07353393]
 [ 0.40881519]]
FI

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.3909632 ]
 [ 0.37277274]
 [ 0.3130422 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01079614]
 [ 0.07039497]
 [ 0.40968665]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49730099]
 [ 0.51759148]
 [ 0.60101274]]
ERROR (target - valor de los final outputs)
[[-0.49730099]
 [ 0.48240852]
 [ 0.39898726]]
Peso actualizado del output layer:  [[-0.49864765  0.96503375 -0.56088777]
 [ 0.98652586 -0.06148172 -0.93400067]
 [-0.21422562  0.78292906  0.64395908]]
Peso actualizado del hidden layer:  [[ 0.25230374 -0.42806395 -0.35121694]
 [ 1.02003447 -0.52495058 -1.79412709]
 [-0.21322111 -0.7841007  -1.27964947]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 29
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.77928088]
 [-2.31907767]
 [-2.06375017]]
HI

ERROR (target - valor de los final outputs)
[[-0.49775733]
 [ 0.48316622]
 [ 0.39877368]]
Peso actualizado del output layer:  [[-0.49748653  0.97021847 -0.56265991]
 [ 0.98304027 -0.06497817 -0.93761256]
 [-0.21972656  0.7904249   0.64822645]]
Peso actualizado del hidden layer:  [[ 0.23890916 -0.42887577 -0.34485841]
 [ 1.03510937 -0.52775842 -1.81892168]
 [-0.22332916 -0.78851943 -1.30200737]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 30
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.77373418]
 [-2.3466801 ]
 [-2.0905268 ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.31567188]
 [ 0.08733002]
 [ 0.11002098]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.13658445]
 [ 0.20378138]
 [ 0.07280324]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46590687]
 [ 0.55076977]
 [ 0.51819278]]
ER

 [-2.11707203]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.31694883]
 [ 0.08515536]
 [ 0.10744855]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.13731712]
 [ 0.2058159 ]
 [ 0.06847686]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46572456]
 [ 0.55127311]
 [ 0.51711253]]
ERROR (target - valor de los final outputs)
[[ 0.53427544]
 [-0.55127311]
 [-0.51711253]]
Peso actualizado del output layer:  [[-0.50135435  0.97074217 -0.56843336]
 [ 0.98434133 -0.06391652 -0.93744489]
 [-0.22155985  0.80158297  0.65557802]]
Peso actualizado del hidden layer:  [[ 0.22573903 -0.44466426 -0.35329793]
 [ 1.05006386 -0.52954144 -1.84256397]
 [-0.23322494 -0.79419116 -1.32529608]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 31
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.22573903]
 [ 1.05006386]
 [

targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.76157752]
 [-2.40186071]
 [-2.14338821]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.31830387]
 [ 0.08303092]
 [ 0.10495069]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.13815793]
 [ 0.20790569]
 [ 0.06415094]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46551535]
 [ 0.55179001]
 [ 0.51603224]]
ERROR (target - valor de los final outputs)
[[ 0.53448465]
 [-0.55179001]
 [-0.51603224]]
Peso actualizado del output layer:  [[-0.50051658  0.9758644  -0.57044398]
 [ 0.98099038 -0.06727752 -0.94102504]
 [-0.2271983   0.80929187  0.66005087]]
Peso actualizado del hidden layer:  [[ 0.21278552 -0.44524349 -0.34634663]
 [ 1.06490017 -0.53247803 -1.8672343 ]
 [-0.24291429 -0.79867593 -1.34708422]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 32
inputs ->  [ 1.  0.  0.]
ta

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46528058]
 [ 0.55231975]
 [ 0.51495072]]
ERROR (target - valor de los final outputs)
[[ 0.53471942]
 [-0.55231975]
 [-0.51495072]]
Peso actualizado del output layer:  [[-0.4998299   0.98095645 -0.57257041]
 [ 0.97769985 -0.07057249 -0.9445888 ]
 [-0.23291011  0.81710505  0.66462268]]
Peso actualizado del hidden layer:  [[ 0.20004133 -0.44574992 -0.33913793]
 [ 1.07962057 -0.53546683 -1.89183317]
 [-0.25240284 -0.80320136 -1.36860776]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 33
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.20004133]
 [ 1.07962057]
 [-0.25240284]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.54984423]
 [ 0.74642217]
 [ 0.43723217]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.21077194]
 [ 0.06806276]
 [ 0.7688204 ]]
FI

[[ 0.18749964]
 [ 1.09422731]
 [-0.26169607]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.54673806]
 [ 0.74917692]
 [ 0.43494682]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.21941703]
 [ 0.06129371]
 [ 0.77511015]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.55463524]
 [ 0.51531863]
 [ 0.68462528]]
ERROR (target - valor de los final outputs)
[[ 0.44536476]
 [-0.51531863]
 [ 0.31537472]]
Peso actualizado del output layer:  [[-0.49501299  0.98707061 -0.57347481]
 [ 0.97007677 -0.07488135 -0.94950643]
 [-0.24282318  0.82400507  0.66800177]]
Peso actualizado del hidden layer:  [[ 0.16775022 -0.44618931 -0.33167445]
 [ 1.10809635 -0.53850327 -1.9163578 ]
 [-0.25077011 -0.80776421 -1.38987165]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 34
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[

targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.16850206]
 [-0.81825741]
 [-1.67074399]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45797388]
 [ 0.30613369]
 [ 0.15832501]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.00797879]
 [ 0.26100519]
 [ 0.25103823]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49800531]
 [ 0.56488337]
 [ 0.56243203]]
ERROR (target - valor de los final outputs)
[[ 0.50199469]
 [ 0.43511663]
 [-0.56243203]]
Peso actualizado del output layer:  [[-0.48864055  1.00030693 -0.57111529]
 [ 0.95989826 -0.08766957 -0.95856322]
 [-0.24502886  0.83712707  0.67571288]]
Peso actualizado del hidden layer:  [[ 0.16315614 -0.44656702 -0.31625852]
 [ 1.12240303 -0.54158285 -1.94095038]
 [-0.27430622 -0.81236133 -1.42532351]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 35
inputs ->  [ 1.  1.  0.]
ta

 [ 0.6459117 ]]
ERROR (target - valor de los final outputs)
[[ 0.42531726]
 [ 0.4715141 ]
 [ 0.3540883 ]]
Peso actualizado del output layer:  [[-0.48268496  1.00908876 -0.57170485]
 [ 0.96169446 -0.08750153 -0.9603594 ]
 [-0.25736075  0.84103498  0.67840923]]
Peso actualizado del hidden layer:  [[ 0.15494189 -0.44304696 -0.30824144]
 [ 1.15240439 -0.5289764  -1.9653832 ]
 [-0.29152427 -0.82552931 -1.44585054]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 36
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.5963465 ]
 [-1.34195522]
 [-2.56290412]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.35518   ]
 [ 0.20718871]
 [ 0.07156434]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ -1.34315931e-04]
 [  2.58275364e-01]
 [  1.33845490e-01]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49996642]
 [

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42362016]
 [ 0.64634132]
 [ 0.2472867 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.30891911]
 [ 0.10923247]
 [ 0.60630474]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.57662141]
 [ 0.527281  ]
 [ 0.6470974 ]]
ERROR (target - valor de los final outputs)
[[ 0.42337859]
 [ 0.472719  ]
 [ 0.3529026 ]]
Peso actualizado del output layer:  [[-0.48260109  1.01400622 -0.57437563]
 [ 0.95864245 -0.09054608 -0.96383725]
 [-0.26344429  0.84926684  0.68337198]]
Peso actualizado del hidden layer:  [[ 0.14303345 -0.44335122 -0.29997575]
 [ 1.16653525 -0.53216826 -1.98973243]
 [-0.30000842 -0.83016422 -1.46613726]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 37
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.60029352]
 [-1.35536544]
 [-2.5963099 ]]
HI

Peso actualizado del hidden layer:  [[ 0.12753135 -0.44737867 -0.29146238]
 [ 1.16491498 -0.55103722 -2.01399538]
 [-0.29982755 -0.82632731 -1.48618784]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 38
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.31984732]
 [ 0.61387776]
 [-1.12615486]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42071296]
 [ 0.64882486]
 [ 0.24487141]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.31671346]
 [ 0.10449934]
 [ 0.61155763]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.57852309]
 [ 0.52610109]
 [ 0.64829604]]
ERROR (target - valor de los final outputs)
[[ 0.42147691]
 [ 0.47389891]
 [ 0.35170396]]
Peso actualizado del output layer:  [[-0.48263658  1.01890249 -0.57713699]
 [ 0.95563791 -0.09353018 -0.96730446]
 [-0.26962184  0.85758166  0.68840513]]
Pe

Peso actualizado del output layer:  [[-0.47851647  1.03043418 -0.57750731]
 [ 0.95762905 -0.08873929 -0.96788904]
 [-0.27256243  0.87117238  0.69543925]]
Peso actualizado del hidden layer:  [[ 0.11617538 -0.44738905 -0.2862632 ]
 [ 1.17960755 -0.55351756 -2.05304967]
 [-0.31363998 -0.83666949 -1.50316818]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 40
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01666203]
 [-0.05378918]
 [ 0.64293413]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49583459]
 [ 0.48655595]
 [ 0.65541642]]
ERROR (target - valor de los final outputs)
[[-0.49583459]
 [-0.48655595]
 [ 0.34458358]]
Peso actualizado del output layer:  [[-0.482926

[[ 0.49603732]
 [ 0.4854123 ]
 [ 0.65623523]]
ERROR (target - valor de los final outputs)
[[-0.49603732]
 [-0.4854123 ]
 [ 0.34376477]]
Peso actualizado del output layer:  [[-0.48323152  1.03279788 -0.58126845]
 [ 0.9498093  -0.09430849 -0.97223553]
 [-0.28362728  0.87701452  0.69973616]]
Peso actualizado del hidden layer:  [[ 0.10489597 -0.44745144 -0.2771384 ]
 [ 1.19348153 -0.55673905 -2.07708437]
 [-0.32170599 -0.84144379 -1.52283002]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 41
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.2771384 ]
 [-2.07708437]
 [-1.52283002]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.43115547]
 [ 0.11134413]
 [ 0.17904516]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.20189887]
 [ 0.22056635]
 [ 0.10344513]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.43345543]
 [ 0.10899735]
 [ 0.17620626]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.2039494]
 [ 0.223606 ]
 [ 0.0977613]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44918866]
 [ 0.55566974]
 [ 0.52442088]]
ERROR (target - valor de los final outputs)
[[-0.44918866]
 [ 0.44433026]
 [-0.52442088]]
Peso actualizado del output layer:  [[-0.4898438   1.03144959 -0.59049668]
 [ 0.94087385 -0.10308632 -0.98171735]
 [-0.28626694  0.88944548  0.70881739]]
Peso actualizado del hidden layer:  [[ 0.0937791  -0.44747949 -0.24841043]
 [ 1.2072595  -0.55997754 -2.11049826]
 [-0.32961497 -0.8462326  -1.55014239]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 42
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.44747949]
 [-0.55997754]
 [-0.8462326 ]]
HIDDE

 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.61444065]
 [-1.4365175 ]
 [-2.78898805]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.35104689]
 [ 0.19208521]
 [ 0.05792215]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.00116593]
 [ 0.25612567]
 [ 0.11050485]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49970852]
 [ 0.56368366]
 [ 0.52759813]]
ERROR (target - valor de los final outputs)
[[-0.49970852]
 [-0.56368366]
 [-0.52759813]]
Peso actualizado del output layer:  [[-0.48037487  1.04970951 -0.58985209]
 [ 0.94612369 -0.09966942 -0.98171585]
 [-0.29884306  0.90544517  0.7163088 ]]
Peso actualizado del hidden layer:  [[ 0.07201921 -0.44744504 -0.2482821 ]
 [ 1.23453561 -0.56649143 -2.14860781]
 [-0.34497846 -0.85584326 -1.58046895]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 44
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [

 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01358565]
 [-0.07617774]
 [ 0.66115578]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49660364]
 [ 0.48096477]
 [ 0.65951997]]
ERROR (target - valor de los final outputs)
[[-0.49660364]
 [-0.48096477]
 [ 0.34048003]]
Peso actualizado del output layer:  [[-0.48546121  1.05211535 -0.59382544]
 [ 0.93847653 -0.10489726 -0.98593474]
 [-0.31028914  0.9116839   0.7209168 ]]
Peso actualizado del hidden layer:  [[ 0.06136998 -0.44738821 -0.23816813]
 [ 1.24803775 -0.56976009 -2.17224762]
 [-0.35244097 -0.86066006 -1.59924508]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 45
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.23816813]
 [-2.17224762]
 [-1.59924508]]
HIDDEN OUTPUTS 

HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01324459]
 [-0.080513  ]
 [ 0.66480351]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4966889 ]
 [ 0.47988262]
 [ 0.6603386 ]]
ERROR (target - valor de los final outputs)
[[-0.4966889 ]
 [-0.47988262]
 [ 0.3396614 ]]
Peso actualizado del output layer:  [[-0.48625102  1.05690615 -0.59714431]
 [ 0.93572807 -0.10740851 -0.98934557]
 [-0.31723256  0.92050859  0.72633098]]
Peso actualizado del hidden layer:  [[ 0.05087084 -0.44730841 -0.22780551]
 [ 1.26145187 -0.5730323  -2.19578304]
 [-0.35976247 -0.86548128 -1.61780853]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 46
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs di

 [-0.52496851]]
Peso actualizado del output layer:  [[-0.48274904  1.06400208 -0.59986687]
 [ 0.93787278 -0.10729005 -0.99201529]
 [-0.31969969  0.9318238   0.73248233]]
Peso actualizado del hidden layer:  [[ 0.04051928 -0.447208   -0.21719343]
 [ 1.27477986 -0.57630498 -2.21921194]
 [-0.36694668 -0.8703046  -1.63616259]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 47
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01298643]
 [-0.08480447]
 [ 0.66844293]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49675344]
 [ 0.47881158]
 [ 0.66115442]]
ERROR (target - valor de los final outputs)
[[-0.49675344]
 [-0.47881158]
 [ 0.33884558]]
Peso actualizado del output lay

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 48
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01280783]
 [-0.08905363]
 [ 0.67207037]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49679809]
 [ 0.47775129]
 [ 0.6619666 ]]
ERROR (target - valor de los final outputs)
[[-0.49679809]
 [-0.47775129]
 [ 0.3380334 ]]
Peso actualizado del output layer:  [[-0.48808247  1.06644616 -0.60397936]
 [ 0.93031948 -0.11227288 -0.99615386]
 [-0.33146861  0.93832754  0.73728182]]
Peso actualizado del hidden layer:  [[ 0.03031302 -0.44708912 -0.20633093]
 [ 1.28802357 -0.57957522 -2.24253222]
 [-0.37399722 -0.87512776 -1.65431046]]
============= FINAL DE FASE DE ENTRENAMIENTO ==

INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01270557]
 [-0.09326193]
 [ 0.67568236]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49682365]
 [ 0.4767014 ]
 [ 0.66277436]]
ERROR (target - valor de los final outputs)
[[-0.49682365]
 [-0.4767014 ]
 [ 0.33722564]]
Peso actualizado del output layer:  [[-0.48911679  1.07119644 -0.60749079]
 [ 0.92765563 -0.11462734 -0.99955215]
 [-0.33876528  0.94731669  0.74281331]]
Peso actualizado del hidden layer:  [[ 0.02024997 -0.44695377 -0.195217  ]
 [ 1.30118478 -0.58284019 -2.26574187]
 [-0.38091759 -0.87994859 -1.67225525]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 49
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (mul

Peso actualizado del output layer:  [[-0.49022543  1.07593421 -0.61106183]
 [ 0.92501627 -0.11693083 -1.00294703]
 [-0.34618356  0.95635572  0.748379  ]]
Peso actualizado del hidden layer:  [[ 0.01032823 -0.44680378 -0.18385052]
 [ 1.31426526 -0.58609719 -2.28883895]
 [-0.3877112  -0.88476499 -1.69      ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 50
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.18385052]
 [-2.28883895]
 [-1.69      ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.4541664 ]
 [ 0.09205154]
 [ 0.15577584]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.22315066]
 [ 0.24894873]
 [ 0.05002457]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44444269]
 [ 0.56191773]
 [ 0.51250353]]
ERROR (target - valor de los final outputs)
[[-0.44444269]
 [ 0.43808227]
 [-0.51250353]]
Pe

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49682062]
 [ 0.4746314 ]
 [ 0.66437379]]
ERROR (target - valor de los final outputs)
[[-0.49682062]
 [-0.4746314 ]
 [ 0.33562621]]
Peso actualizado del output layer:  [[-0.49140491  1.08065986 -0.61469035]
 [ 0.92239958 -0.11918393 -1.00633884]
 [-0.35372524  0.9654423   0.75397668]]
Peso actualizado del hidden layer:  [[  5.46091181e-04  -4.46640799e-01  -1.72230345e-01]
 [  1.32726672e+00  -5.89343665e-01  -2.31182155e+00]
 [ -3.94381364e-01  -8.89574942e-01  -1.70754763e+00]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 51
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.17223034]
 [-2.31182155]
 [-1.70754763]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45704853]
 [ 0.09014863]
 [ 0.15348207]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-

Iteración # 52
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.44646635]
 [-0.59257713]
 [-0.89437649]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.39020125]
 [ 0.35604376]
 [ 0.2902075 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.00552823]
 [ 0.01927547]
 [ 0.4270395 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.50138205]
 [ 0.50481872]
 [ 0.60516651]]
ERROR (target - valor de los final outputs)
[[-0.50138205]
 [ 0.49518128]
 [ 0.39483349]]
Peso actualizado del output layer:  [[-0.50389092  1.07819875 -0.62623759]
 [ 0.91883825 -0.12634307 -1.01400792]
 [-0.36351839  0.97717915  0.76140793]]
Peso actualizado del hidden layer:  [[-0.009098   -0.43304382 -0.14043155]
 [ 1.34019082 -0.59755998 -2.34299489]
 [-0.40093129 -0.89205922 -1.73202953]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.4462818 ]
 [-0.59579525]
 [-0.89916776]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.39024517]
 [ 0.35530626]
 [ 0.28922155]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.00541358]
 [ 0.01766533]
 [ 0.42740429]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.50135339]
 [ 0.50441622]
 [ 0.60525367]]
ERROR (target - valor de los final outputs)
[[-0.50135339]
 [ 0.49558378]
 [ 0.39474633]]
Peso actualizado del output layer:  [[-0.50522471  1.08292338 -0.62994746]
 [ 0.91629621 -0.12850485 -1.01740776]
 [-0.37134506  0.9863677   0.76708417]]
Peso actualizado del hidden layer:  [[-0.01860543 -0.43293709 -0.12823836]
 [ 1.35303919 -0.60077159 -2.36562977]
 [-0.40736411 -0.89681561 -1.74911965]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 53
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.17692072]
 [ 0.26431989]
 [-0.03947339]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45588483]
 [ 0.56569792]
 [ 0.49013293]]
ERROR (target - valor de los final outputs)
[[ 0.54411517]
 [-0.56569792]
 [-0.49013293]]
Peso actualizado del output layer:  [[-0.51151097  1.08319273 -0.63732178]
 [ 0.91861085 -0.12622123 -1.01723105]
 [-0.37561991  0.99894015  0.7755038 ]]
Peso actualizado del hidden layer:  [[-0.02797746 -0.44706979 -0.13003516]
 [ 1.36581342 -0.60318526 -2.38736682]
 [-0.41368284 -0.90247835 -1.76694077]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 54
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.02797746]
 [ 1.36581342]
 [-0.41368284]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.49300609]
 [ 0.79670291]
 [ 0.39802937]]
FI

targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.03721518]
 [ 1.37851504]
 [-0.41989043]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.49069728]
 [ 0.7987524 ]
 [ 0.39654297]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.36631529]
 [-0.06105615]
 [ 0.92383146]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.59056832]
 [ 0.4847407 ]
 [ 0.71582215]]
ERROR (target - valor de los final outputs)
[[ 0.40943168]
 [-0.4847407 ]
 [ 0.28417785]]
Peso actualizado del output layer:  [[-0.50797646  1.08853414 -0.64026177]
 [ 0.9109712  -0.12893945 -1.02151992]
 [-0.38821338  1.00763095  0.78044272]]
Peso actualizado del hidden layer:  [[-0.05620581 -0.44692453 -0.11730234]
 [ 1.39128686 -0.60636841 -2.40977395]
 [-0.4090069  -0.90719948 -1.78364928]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 55
inputs ->  [ 1.  0.  1.]
ta

Peso actualizado del output layer:  [[-0.50943781  1.09321997 -0.64412594]
 [ 0.90843375 -0.13094586 -1.02490476]
 [-0.39645262  1.01694362  0.78619877]]
Peso actualizado del hidden layer:  [[-0.06528791 -0.44677322 -0.10430979]
 [ 1.40385762 -0.60952805 -2.43205858]
 [-0.41511728 -0.91190452 -1.80017494]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 56
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.1695977 ]
 [-1.02820095]
 [-2.21529222]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45770191]
 [ 0.26343304]
 [ 0.09838562]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.00388777]
 [ 0.27474502]
 [ 0.16650307]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49902806]
 [ 0.56825743]
 [ 0.54152987]]
ERROR (target - valor de los final outputs)
[[ 0.50097194]
 [ 0.43174257]
 [-0.54152987]]
Pe

 [-0.42112265 -0.91659187 -1.81652023]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 57
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.16529496]
 [-1.03786092]
 [-2.23764288]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45877009]
 [ 0.26156294]
 [ 0.09642071]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.00510264]
 [ 0.27602089]
 [ 0.1617574 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49872434]
 [ 0.56857042]
 [ 0.5403514 ]]
ERROR (target - valor de los final outputs)
[[ 0.50127566]
 [ 0.43142958]
 [-0.5403514 ]]
Peso actualizado del output layer:  [[-0.50617918  1.10577191 -0.6441741 ]
 [ 0.90005322 -0.14257114 -1.03302787]
 [-0.40206162  1.0308523   0.79421209]]
Peso actualizado del hidden layer:  [[-0.0655026  -0.44661665 -0.08232054]
 [ 1.41511757 -0.61266226 -2.45545987]
 [

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.45182385]
 [ 0.02646928]
 [ 0.72590745]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.61107278]
 [ 0.50661693]
 [ 0.67390655]]
ERROR (target - valor de los final outputs)
[[ 0.38892722]
 [ 0.49338307]
 [ 0.32609345]]
Peso actualizado del output layer:  [[-0.5020131   1.1136781  -0.64697512]
 [ 0.90244126 -0.14173495 -1.03538044]
 [-0.4167639   1.03672539  0.79871457]]
Peso actualizado del hidden layer:  [[-0.0716071  -0.44378797 -0.0687576 ]
 [ 1.44245281 -0.60083544 -2.47752545]
 [-0.4454888  -0.92942578 -1.84298493]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 58
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.58415268]
 [-1.63590808]
 [-3.21789951]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.35797762]
 [ 0.16302262]
 [ 0.03849766]]
FI

targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.53754993]
 [ 0.83023253]
 [-1.37909804]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.36875771]
 [ 0.69640409]
 [ 0.2011539 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.46388185]
 [ 0.02004519]
 [ 0.73798391]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.61393465]
 [ 0.50501113]
 [ 0.67655484]]
ERROR (target - valor de los final outputs)
[[ 0.38606535]
 [ 0.49498887]
 [ 0.32344516]]
Peso actualizado del output layer:  [[-0.50530204  1.12290487 -0.65511866]
 [ 0.89752785 -0.14545897 -1.04212206]
 [-0.43425873  1.05558433  0.81035921]]
Peso actualizado del hidden layer:  [[-0.08889746 -0.44359064 -0.04084239]
 [ 1.46698907 -0.60703276 -2.5212687 ]
 [-0.45670695 -0.93867393 -1.8745286 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 60
inputs ->  [ 1.  1.  1.]
ta

ERROR (target - valor de los final outputs)
[[ 0.38465243]
 [ 0.49577264]
 [ 0.32211917]]
Peso actualizado del output layer:  [[-0.50700188  1.12750334 -0.65925017]
 [ 0.89507787 -0.14725186 -1.0454909 ]
 [-0.44320984  1.06505682  0.81620514]]
Peso actualizado del hidden layer:  [[-0.09734984 -0.44348823 -0.02648867]
 [ 1.47916223 -0.61008437 -2.54294359]
 [-0.46217744 -0.9432639  -1.89004715]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 61
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.56732674]
 [-1.67386573]
 [-3.2954885 ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.36185389]
 [ 0.15790946]
 [ 0.03572628]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.02669223]
 [ 0.26638366]
 [ 0.0387248 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49332734]
 [ 0.56620488]
 [ 0.50967999]]
ER

 [-1.39915097]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.36497398]
 [ 0.70027198]
 [ 0.19795087]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.47577273]
 [ 0.01382428]
 [ 0.75013327]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.61674917]
 [ 0.50345602]
 [ 0.67920774]]
ERROR (target - valor de los final outputs)
[[ 0.38325083]
 [ 0.49654398]
 [ 0.32079226]]
Peso actualizado del output layer:  [[-0.50873471  1.13209185 -0.66341981]
 [ 0.89262995 -0.14899919 -1.04885855]
 [-0.45229755  1.07455611  0.82206546]]
Peso actualizado del hidden layer:  [[-0.10567427 -0.44338364 -0.01187013]
 [ 1.49127384 -0.61310267 -2.56448552]
 [-0.4675586  -0.94782935 -1.90539968]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 62
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.56092803]
 [-1.68631435]
 [

 [-0.4615223   1.08408089  0.8279393 ]]
Peso actualizado del hidden layer:  [[-0.11387111 -0.44327698  0.00301362]
 [ 1.50332521 -0.61608631 -2.58589322]
 [-0.47285263 -0.95236896 -1.92058827]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 63
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.55413447]
 [-1.69865431]
 [-3.34580986]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.36490571]
 [ 0.1546411 ]
 [ 0.03403264]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.03099525]
 [ 0.26879843]
 [ 0.02912923]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49225181]
 [ 0.5667979 ]
 [ 0.50728179]]
ERROR (target - valor de los final outputs)
[[-0.49225181]
 [-0.5667979 ]
 [-0.50728179]]
Peso actualizado del output layer:  [[-0.5072245   1.14299954 -0.66585618]
 [ 0.89469681 -0.14197155 -1.04978349]
 [

Peso actualizado del output layer:  [[-0.51228771  1.14123878 -0.67186865]
 [ 0.88773295 -0.15235852 -1.0555905 ]
 [-0.47088445  1.09362989  0.83382581]]
Peso actualizado del hidden layer:  [[-0.1219407  -0.44316828  0.01816278]
 [ 1.51531761 -0.619034   -2.60716542]
 [-0.47806168 -0.95688152 -1.93561492]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 64
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.54694621]
 [-1.71088182]
 [-3.37055812]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.3665732 ]
 [ 0.15304938]
 [ 0.03322837]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.03323775]
 [ 0.27009672]
 [ 0.02417488]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49169133]
 [ 0.56711665]
 [ 0.50604342]]
ERROR (target - valor de los final outputs)
[[-0.49169133]
 [-0.56711665]
 [-0.50604342]]
Pe

 [ 0.03245099]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.03553932]
 [ 0.27145492]
 [ 0.01911141]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4911161 ]
 [ 0.56745005]
 [ 0.50477771]]
ERROR (target - valor de los final outputs)
[[-0.4911161 ]
 [-0.56745005]
 [-0.50477771]]
Peso actualizado del output layer:  [[-0.51089355  1.15209701 -0.67442018]
 [ 0.88976372 -0.14516787 -1.05654387]
 [-0.4779187   1.10804285  0.84105006]]
Peso actualizado del hidden layer:  [[-0.13017991 -0.44335403  0.03328083]
 [ 1.51384895 -0.63534789 -2.64170427]
 [-0.48159843 -0.95977641 -1.94889223]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 66
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cr

 [-0.48667276 -0.96426033 -1.96362997]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 67
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.02082399]
 [-0.16351048]
 [ 0.73501495]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49479419]
 [ 0.45921321]
 [ 0.6759048 ]]
ERROR (target - valor de los final outputs)
[[-0.49479419]
 [-0.45921321]
 [ 0.3240952 ]]
Peso actualizado del output layer:  [[-0.517299    1.15479206 -0.67914104]
 [ 0.88213227 -0.14878936 -1.06036387]
 [-0.49224324  1.11573105  0.84654209]]
Peso actualizado del hidden layer:  [[-0.13785765 -0.44310271  0.04909897]
 [ 1.5257878  -0.63815947 -2.66264121]
 [-0.48667276 -0.96426033 -1.96362997]]
=======

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 68
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.02168149]
 [-0.16718299]
 [ 0.73787359]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49457984]
 [ 0.45830133]
 [ 0.67653069]]
ERROR (target - valor de los final outputs)
[[-0.49457984]
 [-0.45830133]
 [ 0.32346931]]
Peso actualizado del output layer:  [[-0.51920256  1.15933564 -0.68349607]
 [ 0.8796227  -0.15025768 -1.06373099]
 [-0.50205796  1.12535101  0.85245414]]
Peso actualizado del hidden layer:  [[-0.14540797 -0.44284784  0.06518307]
 [ 1.53767127 -0.64093179 -2.68343921]
 [-0.49166717 -0.96871274 -1.97821058]]
============= FINAL DE FASE DE ENTRENAMIENTO ==

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49435815]
 [ 0.45739392]
 [ 0.6771441 ]]
ERROR (target - valor de los final outputs)
[[-0.49435815]
 [-0.45739392]
 [ 0.3228559 ]]
Peso actualizado del output layer:  [[-0.52112242  1.16386828 -0.68788258]
 [ 0.87710296 -0.15168299 -1.06709718]
 [-0.5120104   1.13499021  0.85837617]]
Peso actualizado del hidden layer:  [[-0.15283118 -0.44258915  0.08153251]
 [ 1.54950051 -0.64366385 -2.70409716]
 [-0.49658363 -0.97313259 -1.99263594]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 69
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.08153251]
 [-2.70409716]
 [-1.99263594]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.52037184]
 [ 0.06273202]
 [ 0.11997827]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.28504071]
 [ 0.3148852 ]
 [-0.0897678 ]]
FI

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 70
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.4423263 ]
 [-0.64635477]
 [-0.97751889]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.3911868 ]
 [ 0.34381145]
 [ 0.27338437]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.00111149]
 [-0.00620754]
 [ 0.42607363]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49972213]
 [ 0.49844812]
 [ 0.6049357 ]]
ERROR (target - valor de los final outputs)
[[-0.49972213]
 [ 0.50155188]
 [ 0.3950643 ]]
Peso actualizado del output layer:  [[-0.53473219  1.16156869 -0.6997179 ]
 [ 0.87429172 -0.15809688 -1.07490929]
 [-0.52479964  1.14743726  0.86642209]]
Peso actualizado del hidden layer:  [[-0.16012761 -0.43045665  0.11907199]
 [ 1.56127665 -0.65101225 -2.73102669]
 [-0.501424   -0.97448291 -2.01282454]]
==

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 71
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.29430313]
 [-3.4049378 ]
 [-3.00567257]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42695072]
 [ 0.0321415 ]
 [ 0.04717026]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.2272646 ]
 [ 0.31861871]
 [-0.14829622]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44342714]
 [ 0.57898758]
 [ 0.46299374]]
ERROR (target - valor de los final outputs)
[[ 0.55657286]
 [-0.57898758]
 [-0.46299374]]
Peso actualizado del output layer:  [[-0.54158883  1.16180928 -0.70754654]
 [ 0.87669668 -0.15513139 -1.07485954]
 [-0.531358    1.16036174  0.8749514 ]]
Peso actualizado del hidden layer:  [[-0.16729764 -0.44406316  0.12221016]
 [ 1.5730008  -0.65301177 -2.75068661]
 [-0.50619013 -0.97958385 -2.0276759 ]]
==

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.23072084]
 [ 0.32204076]
 [-0.15597179]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44257431]
 [ 0.57982152]
 [ 0.46108591]]
ERROR (target - valor de los final outputs)
[[ 0.55742569]
 [-0.57982152]
 [-0.46108591]]
Peso actualizado del output layer:  [[-0.5435665   1.16633326 -0.71198897]
 [ 0.87418132 -0.1564341  -1.07823612]
 [-0.54174484  1.17005664  0.88090809]]
Peso actualizado del hidden layer:  [[-0.17434169 -0.4438533   0.13941962]
 [ 1.58467406 -0.65559363 -2.77083079]
 [-0.51088379 -0.98384815 -2.04157708]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 72
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.17434169]
 [ 1.58467406]
 [-0.51088379]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45652464]
 [ 0.82986546]
 [ 0.37498637]]
FI

inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.25935706]
 [-3.45017627]
 [-3.041848  ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.43552176]
 [ 0.0307636 ]
 [ 0.04557073]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.23422891]
 [ 0.32548096]
 [-0.16381443]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44170903]
 [ 0.58065942]
 [ 0.45913773]]
ERROR (target - valor de los final outputs)
[[ 0.55829097]
 [-0.58065942]
 [-0.45913773]]
Peso actualizado del output layer:  [[-0.54554962  1.17084518 -0.71645975]
 [ 0.87164877 -0.15769426 -1.08161106]
 [-0.55226578  1.17976729  0.88687296]]
Peso actualizado del hidden layer:  [[-0.18126023 -0.44363793  0.15688711]
 [ 1.59629749 -0.65813058 -2.79083175]
 [-0.51550672 -0.98807573 -2.05533059]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 73
in

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.23778793]
 [ 0.32893758]
 [-0.17182775]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44083155]
 [ 0.58150085]
 [ 0.45714844]]
ERROR (target - valor de los final outputs)
[[ 0.55916845]
 [-0.58150085]
 [-0.45714844]]
Peso actualizado del output layer:  [[-0.54753549  1.17534482 -0.72095812]
 [ 0.86909719 -0.15891206 -1.08498426]
 [-0.5629197   1.18949293  0.89284568]]
Peso actualizado del hidden layer:  [[-0.18805382 -0.44341649  0.17461043]
 [ 1.60787214 -0.66062197 -2.81068856]
 [-0.52006061 -0.99226574 -2.06893812]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 74
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.18805382]
 [ 1.60787214]
 [-0.52006061]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45312461]
 [ 0.83311575]
 [ 0.37283806]]
FI

targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.19472308]
 [ 1.61939905]
 [-0.52454709]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45147247]
 [ 0.83471224]
 [ 0.37178959]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.47033318]
 [-0.15047634]
 [ 1.07344953]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.61546261]
 [ 0.46245174]
 [ 0.74525237]]
ERROR (target - valor de los final outputs)
[[ 0.38453739]
 [-0.46245174]
 [ 0.25474763]]
Peso actualizado del output layer:  [[-0.54338915  1.18023854 -0.7248754 ]
 [ 0.86023058 -0.160505   -1.08897959]
 [-0.57872072  1.19890028  0.89832873]]
Peso actualizado del hidden layer:  [[-0.21340038 -0.44318841  0.19258713]
 [ 1.63089851 -0.66306718 -2.83040033]
 [-0.51395024 -0.99641735 -2.08240131]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 75
inputs ->  [ 1.  0.  1.]
ta

inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.20126871]
 [ 1.63087924]
 [-0.52896776]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.449852  ]
 [ 0.83629005]
 [ 0.37075767]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.47500732]
 [-0.15438521]
 [ 1.08081857]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.61656823]
 [ 0.46148018]
 [ 0.74664886]]
ERROR (target - valor de los final outputs)
[[ 0.38343177]
 [-0.46148018]
 [ 0.25335114]]
Peso actualizado del output layer:  [[-0.54530266  1.1847048  -0.72943609]
 [ 0.85756561 -0.16163013 -1.09233921]
 [-0.58966069  1.20866248  0.90432708]]
Peso actualizado del hidden layer:  [[-0.21993471 -0.44295306  0.21081437]
 [ 1.64231194 -0.66546566 -2.84996617]
 [-0.51838739 -1.00052976 -2.09572179]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 76
in

 [ 1.08817074]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.6176636 ]
 [ 0.46052091]
 [ 0.7480371 ]]
ERROR (target - valor de los final outputs)
[[ 0.3823364 ]
 [-0.46052091]
 [ 0.2519629 ]]
Peso actualizado del output layer:  [[-0.54720981  1.18915828 -0.73402198]
 [ 0.8548751  -0.1627136  -1.09569699]
 [-0.60072861  1.21843736  0.91033223]]
Peso actualizado del hidden layer:  [[-0.22634632 -0.44270985  0.22928901]
 [ 1.65367944 -0.66781689 -2.86938526]
 [-0.52276039 -1.00460221 -2.10890114]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 77
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.00294269]
 [-1.21570582]
 [-2.63166154]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.50073567]
 [ 0.22869303]
 [ 0.06712833]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04734809]
 [ 0.31225833]
 [

inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.66539241]
 [ 0.99340804]
 [-1.54378077]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.33952932]
 [ 0.72976055]
 [ 0.17598633]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.56653411]
 [-0.02946396]
 [ 0.84928096]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.63796306]
 [ 0.49263454]
 [ 0.70041629]]
ERROR (target - valor de los final outputs)
[[ 0.36203694]
 [ 0.50736546]
 [ 0.29958371]]
Peso actualizado del output layer:  [[-0.53863853  1.20405854 -0.73447028]
 [ 0.85224487 -0.17099686 -1.10258179]
 [-0.61622198  1.22928637  0.91723995]]
Peso actualizado del hidden layer:  [[-0.22175063 -0.44127449  0.25770937]
 [ 1.67767692 -0.65597199 -2.89013028]
 [-0.54313028 -1.01661744 -2.13001699]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 78
in

INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.67126271]
 [ 1.00244191]
 [-1.55193105]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.33821416]
 [ 0.73153842]
 [ 0.17480754]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.57201855]
 [-0.03182606]
 [ 0.85557201]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.63922881]
 [ 0.49204416]
 [ 0.70173469]]
ERROR (target - valor de los final outputs)
[[ 0.36077119]
 [ 0.50795584]
 [ 0.29826531]]
Peso actualizado del output layer:  [[-0.54050505  1.20845607 -0.73913878]
 [ 0.8495515  -0.17201031 -1.10592628]
 [-0.62758263  1.23908402  0.92325409]]
Peso actualizado del hidden layer:  [[-0.22796081 -0.44109274  0.27670577]
 [ 1.68892207 -0.65827155 -2.90924269]
 [-0.54728443 -1.02060201 -2.1428295 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 79
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
IN

targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.05480161]
 [-1.24686901]
 [-2.69987891]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.51369698]
 [ 0.2232426 ]
 [ 0.0629805 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.0590429 ]
 [ 0.32144607]
 [ 0.00964969]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48524356]
 [ 0.57967663]
 [ 0.5024124 ]]
ERROR (target - valor de los final outputs)
[[ 0.51475644]
 [ 0.42032337]
 [-0.5024124 ]]
Peso actualizado del output layer:  [[-0.55079314  1.21434043 -0.74935325]
 [ 0.83881036 -0.17619861 -1.11325317]
 [-0.64421212  1.26151541  0.93609176]]
Peso actualizado del hidden layer:  [[-0.2409745  -0.44164597  0.31539675]
 [ 1.69727397 -0.67674094 -2.9470136 ]
 [-0.54745387 -1.02047812 -2.16805152]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 81
inputs ->  [ 1.  1.  0.]
ta

 [ 0.50034268]]
ERROR (target - valor de los final outputs)
[[ 0.51551691]
 [ 0.41975011]
 [-0.50034268]]
Peso actualizado del output layer:  [[-0.5526586   1.21870981 -0.75407701]
 [ 0.83599398 -0.17707001 -1.11657915]
 [-0.65591056  1.27131641  0.94210863]]
Peso actualizado del hidden layer:  [[-0.24675541 -0.44135432  0.33508157]
 [ 1.70844264 -0.67885001 -2.96567072]
 [-0.55144381 -1.0243403  -2.18046391]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 82
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.68810973]
 [ 1.02959263]
 [-1.5757841 ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.33445371]
 [ 0.73683691]
 [ 0.17139338]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.58837727]
 [-0.03869589]
 [ 0.87451027]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.64299273]
 [ 0.49032723]
 [

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48371198]
 [ 0.58082688]
 [ 0.49822938]]
ERROR (target - valor de los final outputs)
[[ 0.51628802]
 [ 0.41917312]
 [-0.49822938]]
Peso actualizado del output layer:  [[-0.55450239  1.22306461 -0.75882228]
 [ 0.83314141 -0.17790019 -1.11990254]
 [-0.66772132  1.28112688  0.9481316 ]]
Peso actualizado del hidden layer:  [[-0.25242275 -0.44105133  0.35498551]
 [ 1.7195728  -0.68090976 -2.98417477]
 [-0.55537975 -1.02815852 -2.19274578]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 83
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.69347408]
 [ 1.03866304]
 [-1.58353827]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.33326069]
 [ 0.73859196]
 [ 0.17029496]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.59380105]
 [-0.04091579]
 [ 0.88084586]]
FI

Peso actualizado del output layer:  [[-0.55632221  1.22740449 -0.76358861]
 [ 0.83025111 -0.17868919 -1.1232231 ]
 [-0.67964106  1.29094635  0.95416059]]
Peso actualizado del hidden layer:  [[-0.25797836 -0.44073653  0.37510278]
 [ 1.73066526 -0.68292002 -3.00252516]
 [-0.55926301 -1.0319322  -2.20489853]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 84
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.69871489]
 [ 1.04774524]
 [-1.59119521]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.33209722]
 [ 0.74034169]
 [ 0.16921581]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.59921136]
 [-0.04310171]
 [ 0.88719363]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.64547586]
 [ 0.48922624]
 [ 0.7083107 ]]
ERROR (target - valor de los final outputs)
[[ 0.35452414]
 [ 0.51077376]
 [ 0.2916893 ]]
Pe

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 85
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.30715488]
 [-1.93622577]
 [-3.83157757]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42380935]
 [ 0.12606308]
 [ 0.02121554]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.09237924]
 [ 0.30970703]
 [-0.1104811 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4769216 ]
 [ 0.57681375]
 [ 0.47240778]]
ERROR (target - valor de los final outputs)
[[-0.4769216 ]
 [-0.57681375]
 [-0.47240778]]
Peso actualizado del output layer:  [[-0.54861722  1.24054021 -0.76625223]
 [ 0.83691948 -0.16773717 -1.12378977]
 [-0.69620414  1.30252113  0.96047029]]
Peso actualizado del hidden layer:  [[-0.26016615 -0.43715146  0.39805949]
 [ 1.7433172  -0.68328421 -3.03295265]
 [-0.56988132 -1.04244727 -2.21576084]]
==

Peso actualizado del output layer:  [[-0.55299532  1.23884767 -0.77242696]
 [ 0.82974948 -0.1779411  -1.12926238]
 [-0.71032713  1.30794435  0.96551902]]
Peso actualizado del hidden layer:  [[-0.26821693 -0.43952442  0.41595237]
 [ 1.76651968 -0.67301189 -3.03876283]
 [-0.57482201 -1.04728927 -2.22882221]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 86
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.29178899]
 [-1.94525504]
 [-3.85093348]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42756595]
 [ 0.12507167]
 [ 0.02081731]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.09566934]
 [ 0.31204697]
 [-0.11861427]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47610089]
 [ 0.57738482]
 [ 0.47038115]]
ERROR (target - valor de los final outputs)
[[-0.47610089]
 [-0.57738482]
 [-0.47038115]]
Pe

Iteración # 87
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.2761113 ]
 [-1.95411607]
 [-3.87007   ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.4314074 ]
 [ 0.12410524]
 [ 0.02043079]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.09899034]
 [ 0.31440923]
 [-0.12692065]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4752726 ]
 [ 0.57796114]
 [ 0.46831236]]
ERROR (target - valor de los final outputs)
[[-0.4752726 ]
 [-0.57796114]
 [-0.46831236]]
Peso actualizado del output layer:  [[-0.55204324  1.24908671 -0.77593681]
 [ 0.83097523 -0.16907839 -1.13045665]
 [-0.72062804  1.32221233  0.97255889]]
Peso actualizado del hidden layer:  [[-0.27059705 -0.43631917  0.43960454]
 [ 1.76533278 -0.68704363 -3.06877113]
 [-0.57741726 -1.04978863 -2.23946175]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

[[ 0.43533144]
 [ 0.1231635 ]
 [ 0.02005556]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.10234002]
 [ 0.31679035]
 [-0.13540087]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4744373 ]
 [ 0.57854184]
 [ 0.4662014 ]]
ERROR (target - valor de los final outputs)
[[-0.4744373 ]
 [-0.57854184]
 [-0.4662014 ]]
Peso actualizado del output layer:  [[-0.55370622  1.25333599 -0.7808077 ]
 [ 0.82793992 -0.16968704 -1.13378392]
 [-0.73298108  1.33206861  0.97861159]]
Peso actualizado del hidden layer:  [[-0.27565784 -0.43588437  0.46065993]
 [ 1.77628628 -0.68885024 -3.08644796]
 [-0.58111282 -1.05338943 -2.25112534]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 89
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
F

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 90
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04516234]
 [-0.24535266]
 [ 0.78723517]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48871133]
 [ 0.4389677 ]
 [ 0.68723736]]
ERROR (target - valor de los final outputs)
[[-0.48871133]
 [-0.4389677 ]
 [ 0.31276264]]
Peso actualizado del output layer:  [[-0.56052043  1.25612545 -0.78592971]
 [ 0.8186593  -0.17197992 -1.1373847 ]
 [-0.75049269  1.34052053  0.9844425 ]]
Peso actualizado del hidden layer:  [[-0.28061916 -0.43543713  0.48189382]
 [ 1.78720437 -0.69060816 -3.1039694 ]
 [-0.58476178 -1.05694307 -2.26266617]]
============= FINAL DE FASE DE ENTRENAMIENTO ==

INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.50329821]
 [-3.12133516]
 [-2.27408561]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.62323411]
 [ 0.04223573]
 [ 0.09329204]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.37552592]
 [ 0.39043592]
 [-0.32356245]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.40720644]
 [ 0.59638763]
 [ 0.4198078 ]]
ERROR (target - valor de los final outputs)
[[-0.40720644]
 [ 0.40361237]
 [-0.4198078 ]]
Peso actualizado del output layer:  [[-0.56824956  1.25425275 -0.79693493]
 [ 0.81008115 -0.17788665 -1.14609039]
 [-0.75968152  1.35376245  0.99386656]]
Peso actualizado del hidden layer:  [[-0.28548394 -0.43497757  0.52389778]
 [ 1.79808758 -0.6923175  -3.12599059]
 [-0.58836534 -1.06044916 -2.27878275]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 91
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
IN

ERROR (target - valor de los final outputs)
[[-0.49669259]
 [ 0.50860206]
 [ 0.40025423]]
Peso actualizado del output layer:  [[-0.57598925  1.25806127 -0.80275719]
 [ 0.81295081 -0.17794418 -1.14849085]
 [-0.77867349  1.36322783  0.99899929]]
Peso actualizado del hidden layer:  [[-0.29025528 -0.42525232  0.54537878]
 [ 1.80893638 -0.69774922 -3.14312931]
 [-0.59192474 -1.05981688 -2.29002901]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 92
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.12012646]
 [-3.84087853]
 [-3.34984589]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.52999555]
 [ 0.02102326]
 [ 0.03390021]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.3088184 ]
 [ 0.39103281]
 [-0.34801533]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.42340318]
 [ 0.5965313 ]
 [ 0.41386378]]
ER

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.31300917]
 [ 0.39426305]
 [-0.35962622]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.42238041]
 [ 0.59730852]
 [ 0.41105005]]
ERROR (target - valor de los final outputs)
[[ 0.57761959]
 [-0.59730852]
 [-0.41105005]]
Peso actualizado del output layer:  [[-0.58244265  1.25813561 -0.81085742]
 [ 0.81471834 -0.17413764 -1.14853718]
 [-0.78758188  1.37633091  1.00755243]]
Peso actualizado del hidden layer:  [[-0.29493645 -0.43733152  0.55458589]
 [ 1.8197512  -0.69877524 -3.1595773 ]
 [-0.59544118 -1.06381043 -2.30179194]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 93
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.29493645]
 [ 1.8197512 ]
 [-0.59544118]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42679578]
 [ 0.86053627]
 [ 0.35538737]]
FI

 [-0.80033207  1.38623759  1.01364543]]
Peso actualizado del hidden layer:  [[-0.29953083 -0.43689002  0.5764422 ]
 [ 1.83053242 -0.70028966 -3.1764075 ]
 [-0.59891588 -1.06711326 -2.31279609]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 94
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.29953083]
 [ 1.83053242]
 [-0.59891588]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42567218]
 [ 0.86182514]
 [ 0.35459176]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.55371256]
 [-0.21716394]
 [ 1.21088732]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.6349965 ]
 [ 0.44592138]
 [ 0.77045591]]
ERROR (target - valor de los final outputs)
[[ 0.3650035 ]
 [-0.44592138]
 [ 0.22954409]]
Peso actualizado del output layer:  [[-0.5763412   1.26261397 -0.81532486]
 [ 0.80366358 -0.17481562 -1.15231293]
 [

[[ 0.63595445]
 [ 0.44515328]
 [ 0.77171575]]
ERROR (target - valor de los final outputs)
[[ 0.36404555]
 [-0.44515328]
 [ 0.22828425]]
Peso actualizado del output layer:  [[-0.57774136  1.26678241 -0.82028105]
 [ 0.80025185 -0.1751553  -1.15560244]
 [-0.81848071  1.39595369  1.01942554]]
Peso actualizado del hidden layer:  [[-0.32244843 -0.4364371   0.59842997]
 [ 1.8514161  -0.70175538 -3.19308248]
 [-0.59209564 -1.07036705 -2.32368477]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 95
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.27598154]
 [-1.34166637]
 [-2.91578041]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.56856077]
 [ 0.20723616]
 [ 0.05137897]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.10440789]
 [ 0.35449905]
 [-0.12192365]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[

Iteración # 96
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.29367996]
 [-1.3475406 ]
 [-2.92996763]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.57289681]
 [ 0.20627274]
 [ 0.05069188]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.10775275]
 [ 0.35672605]
 [-0.13254834]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47308785]
 [ 0.58824767]
 [ 0.46691135]]
ERROR (target - valor de los final outputs)
[[ 0.52691215]
 [ 0.41175233]
 [-0.46691135]]
Peso actualizado del output layer:  [[-0.57553981  1.27818931 -0.82229037]
 [ 0.79214272 -0.18493731 -1.1627593 ]
 [-0.82966007  1.40931683  1.0269418 ]]
Peso actualizado del hidden layer:  [[-0.31682092 -0.43597346  0.6305791 ]
 [ 1.86106817 -0.70317271 -3.21059576]
 [-0.60220466 -1.07357154 -2.34115571]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.31937091]
 [ 0.76263518]
 [ 0.1567989 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.66856154]
 [-0.06871653]
 [ 0.97119324]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.66118099]
 [ 0.48282762]
 [ 0.72535727]]
ERROR (target - valor de los final outputs)
[[ 0.33881901]
 [ 0.51717238]
 [ 0.27464273]]
Peso actualizado del output layer:  [[-0.56927647  1.28500268 -0.82664079]
 [ 0.79439762 -0.18314327 -1.16552172]
 [-0.84925838  1.41684093  1.03246215]]
Peso actualizado del hidden layer:  [[-0.3214967  -0.43583212  0.65279321]
 [ 1.88493443 -0.69133115 -3.22691775]
 [-0.61343841 -1.08465004 -2.35175317]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 97
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.1045356 ]
 [-2.03331446]
 [-4.04984161]]
HI

Iteración # 99
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.05539839]
 [-0.27695586]
 [ 0.80157953]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48615394]
 [ 0.43120024]
 [ 0.69031226]]
ERROR (target - valor de los final outputs)
[[-0.48615394]
 [-0.43120024]
 [ 0.30968774]]
Peso actualizado del output layer:  [[-0.5736299   1.2935245  -0.83069138]
 [ 0.78821312 -0.17511852 -1.16700632]
 [-0.86573625  1.4296569   1.03923841]]
Peso actualizado del hidden layer:  [[-0.32132926 -0.43090812  0.67962708]
 [ 1.88394335 -0.70426799 -3.2546432 ]
 [-0.61570508 -1.08674749 -2.36123275]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 99
inputs ->  [ 0.  0.  1.]
targets

HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.0676392 ]
 [-2.04709197]
 [-4.08338192]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.48309665]
 [ 0.11434655]
 [ 0.01657115]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.14033077]
 [ 0.34309613]
 [-0.23992528]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46497477]
 [ 0.58494241]
 [ 0.44030476]]
ERROR (target - valor de los final outputs)
[[-0.46497477]
 [-0.58494241]
 [-0.44030476]]
Peso actualizado del output layer:  [[-0.56926461  1.29890416 -0.83555793]
 [ 0.7914346  -0.17363456 -1.17003036]
 [-0.87353788  1.44081577  1.04552903]]
Peso actualizado del hidden layer:  [[-0.32548143 -0.43036138  0.70216561]
 [ 1.89452745 -0.70555119 -3.27060552]
 [-0.61895446 -1.08981232 -2.37162034]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============


In [32]:
# test the neural network

# scorecard for how well the network performs, initially empty
scorecard = []

# go through all the records in the test data set
for record in test_data_list:
    # split the record by the ',' commas
    all_values = record.split(',')
    # correct answer is first value
    correct_label = int(all_values[0])
    # scale and shift the inputs
    # inputs = (numpy.asfarray(all_values[1:]) / 255.0 * 0.99) + 0.01
    inputs = (numpy.asfarray(all_values[0:3]) / 1.0) + 0.00
    # query the network
    outputs = n.query(inputs)
    print("Outputs -> ", outputs)
    # the index of the highest value corresponds to the label
    label = numpy.argmax(outputs)
    # append correct or incorrect to list
    if (label == correct_label):
        # network's answer matches correct answer, add 1 to scorecard
        scorecard.append(1)
    else:
        # network's answer doesn't match correct answer, add 0 to scorecard
        scorecard.append(0)
        pass
    
    pass

Outputs ->  [[ 0.48587615]
 [ 0.4303373 ]
 [ 0.69063127]]
Outputs ->  [[ 0.39933321]
 [ 0.60307856]
 [ 0.39038385]]
Outputs ->  [[ 0.49803087]
 [ 0.48918032]
 [ 0.59693008]]
Outputs ->  [[ 0.4187785 ]
 [ 0.60023299]
 [ 0.39164006]]
Outputs ->  [[ 0.64436543]
 [ 0.44202221]
 [ 0.77708602]]
Outputs ->  [[ 0.47021545]
 [ 0.59241776]
 [ 0.45490246]]
Outputs ->  [[ 0.66437163]
 [ 0.48423896]
 [ 0.72769928]]
Outputs ->  [[ 0.46264257]
 [ 0.58488894]
 [ 0.43767966]]


In [28]:
# calculate the performance score, the fraction of correct answers
scorecard_array = numpy.asarray(scorecard)
print ("performance = ", scorecard_array.sum() / scorecard_array.size)

performance =  0.125
