In [24]:
# python notebook for Make Your Own Neural Network
# code for a 3-layer neural network, and code for learning the MNIST dataset
# (c) Tariq Rashid, 2016
# license is GPLv2

In [25]:
import numpy
# scipy.special for the sigmoid function expit()
import scipy.special
# library for plotting arrays
import matplotlib.pyplot
# ensure the plots are inside this notebook, not an external window
%matplotlib inline

In [54]:
# neural network class definition
class neuralNetwork:
    
    
    # initialise the neural network
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        # set number of nodes in each input, hidden, output layer
        self.inodes = inputnodes
        self.hnodes = hiddennodes
        self.onodes = outputnodes
        
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc 
        #self.wih = numpy.random.normal(0.0, pow(self.inodes, -0.5), (self.hnodes, self.inodes))
        self.wih = numpy.random.normal(0.0, 0.5, (self.hnodes, self.inodes))
        #self.who = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.onodes, self.hnodes))
        self.who = numpy.random.normal(0.0, 0.5, (self.hnodes, self.inodes))
        print("wih: ", self.wih)
        print("who: ", self.who)

        # learning rate
        self.lr = learningrate
        
        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)
        
        pass

    
    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        print("INPUTS")
        print(inputs)
        print("===========================")
        targets = numpy.array(targets_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        print("HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)")
        print(hidden_inputs)
        print("===========================")
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        print("HIDDEN OUTPUTS (después de aplicar la función sigmoide)")
        print(hidden_outputs)
        print("===========================")
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        print("FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)")
        print(final_inputs)
        print("===========================")
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        print("FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)")
        print(final_outputs)
        print("===========================")
        
        # output layer error is the (target - actual)
        output_errors = targets - final_outputs
        print("ERROR (target - valor de los final outputs)")
        print(output_errors)
        print("===========================")
        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = numpy.dot(self.who.T, output_errors) 
        
        # update the weights for the links between the hidden and output layers
        print("Peso actualizado del output layer: ", self.who)
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        
        # update the weights for the links between the input and hidden layers
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        print("Peso actualizado del hidden layer: ", self.wih)
        
        print("============= FINAL DE FASE DE ENTRENAMIENTO ==============")
        
        pass

    
    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = numpy.array(inputs_list, ndmin=2).T
        
        # calculate signals into hidden layer
        hidden_inputs = numpy.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)
        
        # calculate signals into final output layer
        final_inputs = numpy.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)
        
        return final_outputs

In [55]:
# number of input, hidden and output nodes
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# learning rate
learning_rate = 0.1

# create instance of neural network
n = neuralNetwork(input_nodes,hidden_nodes,output_nodes, learning_rate)

wih:  [[-0.41103776 -0.23514698 -0.20896141]
 [-0.28968639 -0.20417809  0.81662542]
 [ 0.28036671 -0.07076208  0.36728809]]
who:  [[ 0.05734282 -0.19655358 -0.17788809]
 [ 0.57553265 -0.66679564  0.13008393]
 [ 0.15773582 -0.28793691 -0.26157918]]


In [56]:
# load the mnist training data CSV file into a list
training_data_file = open("mnist_dataset/contador.csv", 'r')
training_data_list = training_data_file.readlines()
training_data_file.close()

In [57]:
# train the neural network

# epochs is the number of times the training data set is used for training
epochs = 100

for e in range(epochs):
    # go through all records in the training data set
    contador = 1
    for record in training_data_list:
        print("Iteración #", e)
        # split the record by the ',' commas
        all_values = record.split(',')
        # scale and shift the inputs
        inputs = (numpy.asfarray(all_values[0:3]) / 1.0) + 0.00
        # inputs = (numpy.asfarray(all_values[0:3]) / 255.0 * 0.99) + 0.01
        # create the target output values (all 0.01, except the desired label which is 0.99)
        # targets = numpy.zeros(output_nodes) + 0.01
        target_values = training_data_list[contador].split(',')
        targets = (numpy.asfarray(target_values[0:3]) / 1.0) + 0.00
        print("inputs -> ", inputs)
        print("targets -> ", targets)
        # all_values[0] is the target label for this record
        # targets[int(all_values[0])] = 0.99
        n.train(inputs, targets)
        contador += 1
        if(contador == 8):
            contador = 0
        pass
    pass

Iteración # 0
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15854943]
 [ 0.01941047]
 [-0.19589014]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46044547]
 [ 0.50485247]
 [ 0.45118347]]
ERROR (target - valor de los final outputs)
[[-0.46044547]
 [-0.50485247]
 [ 0.54881653]]
Peso actualizado del output layer:  [[ 0.05734282 -0.19655358 -0.17788809]
 [ 0.57553265 -0.66679564  0.13008393]
 [ 0.15773582 -0.28793691 -0.26157918]]
Peso actualizado del hidden layer:  [[-0.41103776 -0.23514698 -0.20896141]
 [-0.28968639 -0.20417809  0.81662542]
 [ 0.28036671 -0.07076208  0.36728809]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 0
inputs ->  [ 0.  0.  1.]
targets -

ERROR (target - valor de los final outputs)
[[ 0.53498211]
 [ 0.4936867 ]
 [ 0.54783105]]
Peso actualizado del output layer:  [[ 0.05831128 -0.18828184 -0.16397974]
 [ 0.57637143 -0.66107085  0.13400749]
 [ 0.17038098 -0.29329303 -0.25740364]]
Peso actualizado del hidden layer:  [[-0.39701682 -0.2227476  -0.21012161]
 [-0.31760515 -0.22405158  0.82125614]
 [ 0.26314313 -0.07882347  0.38280045]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 1
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.82988604]
 [ 0.27959941]
 [ 0.56712011]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.30366917]
 [ 0.56944801]
 [ 0.63809839]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.18525805]
 [-0.10766967]
 [-0.27046347]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4538175 ]
 [ 0.47310856]
 [ 0.43279332]]
ERR

 [-0.25938623]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.44720998]
 [ 0.47208744]
 [ 0.43551459]]
ERROR (target - valor de los final outputs)
[[ 0.55279002]
 [-0.47208744]
 [-0.43551459]]
Peso actualizado del output layer:  [[ 0.04540381 -0.20240218 -0.16868666]
 [ 0.58340181 -0.6513      0.14368789]
 [ 0.19403291 -0.29591034 -0.24574531]]
Peso actualizado del hidden layer:  [[-0.39892304 -0.22531426 -0.23167667]
 [-0.31926901 -0.22045226  0.85657046]
 [ 0.25206314 -0.08250207  0.40796369]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 4
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.39892304]
 [-0.31926901]
 [ 0.25206314]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.40157112]
 [ 0.4208539 ]
 [ 0.56268424]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15150657]
 [ 0.03210701]
 [-

HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.63716606]
 [ 0.54148281]
 [ 0.65527586]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.34588744]
 [ 0.63215729]
 [ 0.65819838]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.19422643]
 [-0.13401475]
 [-0.27990573]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45159546]
 [ 0.46654637]
 [ 0.43047689]]
ERROR (target - valor de los final outputs)
[[ 0.54840454]
 [ 0.53345363]
 [-0.43047689]]
Peso actualizado del output layer:  [[ 0.05680326 -0.18524246 -0.14702496]
 [ 0.57426229 -0.66267465  0.13106953]
 [ 0.20242825 -0.30095834 -0.2425866 ]]
Peso actualizado del hidden layer:  [[-0.39399836 -0.22303804 -0.23183928]
 [-0.33218314 -0.22364859  0.85852617]
 [ 0.24051107 -0.08492858  0.41898161]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 5
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HID

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.18874414]
 [-0.13272925]
 [-0.27935684]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45295355]
 [ 0.46686632]
 [ 0.43061146]]
ERROR (target - valor de los final outputs)
[[ 0.54704645]
 [ 0.53313368]
 [-0.43061146]]
Peso actualizado del output layer:  [[ 0.05740309 -0.1827684  -0.14100897]
 [ 0.57478759 -0.66109503  0.13238513]
 [ 0.20960019 -0.30489617 -0.24098874]]
Peso actualizado del hidden layer:  [[-0.39086923 -0.22073228 -0.23803769]
 [-0.33882949 -0.22676324  0.86837111]
 [ 0.23436364 -0.0872928   0.42793515]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 6
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.61160152]
 [-0.56559274]
 [ 0.14707084]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.35169396]
 [ 0.3622544 ]
 [ 0.53670158]]
FIN

[[-0.1835184 ]
 [-0.13159597]
 [-0.27903339]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45424873]
 [ 0.4671484 ]
 [ 0.43069077]]
ERROR (target - valor de los final outputs)
[[ 0.54575127]
 [ 0.5328516 ]
 [-0.43069077]]
Peso actualizado del output layer:  [[ 0.05792595 -0.18045651 -0.13516516]
 [ 0.57527451 -0.6595553   0.13365431]
 [ 0.21681505 -0.3089717  -0.23953053]]
Peso actualizado del hidden layer:  [[-0.38771418 -0.21839346 -0.24453949]
 [-0.34532191 -0.22980405  0.87842355]
 [ 0.22840494 -0.08959946  0.43685504]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 7
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.60610764]
 [-0.57512597]
 [ 0.13880548]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.35294761]
 [ 0.36005488]
 [ 0.53464576]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-

 [ 0.21461911 -0.09405728  0.45219843]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 9
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.65053828]
 [ 0.55555914]
 [ 0.66681754]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.34286825]
 [ 0.63542439]
 [ 0.66079019]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.17378883]
 [-0.12975785]
 [-0.27903573]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45666182]
 [ 0.46760598]
 [ 0.43069019]]
ERROR (target - valor de los final outputs)
[[ 0.54333818]
 [ 0.53239402]
 [-0.43069019]]
Peso actualizado del output layer:  [[ 0.05875716 -0.17629125 -0.12396527]
 [ 0.57613967 -0.65658316  0.13606604]
 [ 0.23139796 -0.31752172 -0.23700972]]
Peso actualizado del hidden layer:  [[-0.3813223  -0.21360228 -0.25844629]
 [-0.35788345 -0.23569332  0.89914484]
 [ 

 [ 0.20911064 -0.09621632  0.46095914]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 10
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.65455444]
 [ 0.5599364 ]
 [ 0.67006978]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.34196394]
 [ 0.63643782]
 [ 0.66151878]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.16926273]
 [-0.12903978]
 [-0.27934901]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.45778506]
 [ 0.46778475]
 [ 0.43061338]]
ERROR (target - valor de los final outputs)
[[ 0.54221494]
 [ 0.53221525]
 [-0.43061338]]
Peso actualizado del output layer:  [[ 0.05907336 -0.17442472 -0.11859558]
 [ 0.5765209  -0.65514503  0.13721446]
 [ 0.23877781 -0.32198954 -0.23593599]]
Peso actualizado del hidden layer:  [[-0.37808312 -0.21114262 -0.26584823]
 [-0.36397045 -0.23855537  0.90981085]
 [

Iteración # 11
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.58344866]
 [-0.61131016]
 [ 0.10796522]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.35813944]
 [ 0.35176039]
 [ 0.52696512]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.08989781]
 [ 0.05874742]
 [-0.15786112]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47754067]
 [ 0.51468263]
 [ 0.46061647]]
ERROR (target - valor de los final outputs)
[[ 0.52245933]
 [ 0.48531737]
 [ 0.53938353]]
Peso actualizado del output layer:  [[ 0.0639103  -0.16412761 -0.10447184]
 [ 0.58138694 -0.64529004  0.14710138]
 [ 0.24262523 -0.33331028 -0.2419694 ]]
Peso actualizado del hidden layer:  [[-0.36455133 -0.19837332 -0.27354744]
 [-0.38313521 -0.25456668  0.92067864]
 [ 0.20346443 -0.10116795  0.47223125]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.09969357]
 [ 0.04144888]
 [-0.1643191 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47509723]
 [ 0.51036074]
 [ 0.45901241]]
ERROR (target - valor de los final outputs)
[[-0.47509723]
 [-0.51036074]
 [ 0.54098759]]
Peso actualizado del output layer:  [[ 0.06524839 -0.16462282 -0.10001271]
 [ 0.58244325 -0.64646306  0.14691756]
 [ 0.25174489 -0.33944648 -0.2409366 ]]
Peso actualizado del hidden layer:  [[-0.37006168 -0.20462686 -0.29045557]
 [-0.37611844 -0.24446616  0.94459171]
 [ 0.200068   -0.10151275  0.48264818]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 13
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46019773]
 [ 0.46572339]
 [ 0.43157533]]
ERROR (target - valor de los final outputs)
[[-0.46019773]
 [ 0.53427661]
 [-0.43157533]]
Peso actualizado del output layer:  [[ 0.05944256 -0.16913373 -0.10105331]
 [ 0.57634841 -0.65151033  0.14155789]
 [ 0.26608591 -0.33761101 -0.23352505]]
Peso actualizado del hidden layer:  [[-0.36669487 -0.20198179 -0.29476351]
 [-0.38182668 -0.24715867  0.95338134]
 [ 0.19510111 -0.10353793  0.49657918]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 14
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.20198179]
 [-0.24715867]
 [-0.10353793]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.44967552]
 [ 0.43852297]
 [ 0.47413862]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.10452552]
 [ 0.05125283]
 [-0.14761639]]
FI

 [ 0.26708674 -0.34931579 -0.23963943]]
Peso actualizado del hidden layer:  [[-0.3632906  -0.19927568 -0.3074689 ]
 [-0.38744109 -0.24982382  0.96736641]
 [ 0.19027222 -0.10553194  0.49999091]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 15
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.3074689 ]
 [ 0.96736641]
 [ 0.49999091]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42373267]
 [ 0.72459426]
 [ 0.62245719]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15633647]
 [-0.13807606]
 [-0.27722516]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46099529]
 [ 0.46553572]
 [ 0.4311342 ]]
ERROR (target - valor de los final outputs)
[[-0.46099529]
 [ 0.53446428]
 [-0.4311342 ]]
Peso actualizado del output layer:  [[ 0.05951127 -0.16783745 -0.09629464]
 [ 0.57660193 -0.6502009   0.14254907]
 [

[[-0.15328463]
 [-0.13891947]
 [-0.27920743]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4617537 ]
 [ 0.46532588]
 [ 0.4306481 ]]
ERROR (target - valor de los final outputs)
[[-0.4617537 ]
 [ 0.53467412]
 [-0.4306481 ]]
Peso actualizado del output layer:  [[ 0.05953368 -0.1666531  -0.0916555 ]
 [ 0.57682799 -0.64890955  0.14351636]
 [ 0.28159426 -0.34771642 -0.23243345]]
Peso actualizado del hidden layer:  [[-0.35984702 -0.19650468 -0.31252103]
 [-0.39296805 -0.25246654  0.97666365]
 [ 0.18557575 -0.10749736  0.51377326]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 16
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.19650468]
 [-0.25246654]
 [-0.10749736]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.4510313 ]
 [ 0.43721649]
 [ 0.47315151]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[

Peso actualizado del hidden layer:  [[-0.35636219 -0.1936649  -0.32565122]
 [-0.39841359 -0.25509151  0.99093157]
 [ 0.18100641 -0.10943662  0.51726027]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 17
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.32565122]
 [ 0.99093157]
 [ 0.51726027]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.41929912]
 [ 0.72927189]
 [ 0.6265069 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15038444]
 [-0.13984826]
 [-0.28137053]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46247458]
 [ 0.4650948 ]
 [ 0.4301178 ]]
ERROR (target - valor de los final outputs)
[[-0.46247458]
 [ 0.5349052 ]
 [-0.4301178 ]]
Peso actualizado del output layer:  [[ 0.05951283 -0.16557605 -0.08713098]
 [ 0.57702743 -0.64763444  0.14446167]
 [ 0.28948842 -0.35293533 -0.23202771]]
Pe

 [ 0.52587098]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.41698087]
 [ 0.73164939]
 [ 0.62851957]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.14762951]
 [-0.14085879]
 [-0.2837117 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46315951]
 [ 0.46484341]
 [ 0.42954404]]
ERROR (target - valor de los final outputs)
[[-0.46315951]
 [ 0.53515659]
 [-0.42954404]]
Peso actualizado del output layer:  [[ 0.05945163 -0.16460187 -0.08271634]
 [ 0.57720102 -0.6463738   0.14538677]
 [ 0.29748232 -0.35826183 -0.2317097 ]]
Peso actualizado del hidden layer:  [[-0.35283407 -0.19075243 -0.3314461 ]
 [-0.40378343 -0.25770322  1.00073375]
 [ 0.17655914 -0.11135198  0.53090592]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 18
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.19075243]
 [-0.25770322]
 [

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 19
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.18776334]
 [-0.26030592]
 [-0.11324556]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45319659]
 [ 0.43528851]
 [ 0.47171883]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.09063928]
 [ 0.06056555]
 [-0.13747102]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47735568]
 [ 0.51513676]
 [ 0.46568627]]
ERROR (target - valor de los final outputs)
[[-0.47735568]
 [ 0.48486324]
 [ 0.53431373]]
Peso actualizado del output layer:  [[ 0.05457076 -0.17219328 -0.08567986]
 [ 0.58287124 -0.63534955  0.15469098]
 [ 0.30122463 -0.37140591 -0.23810003]]
Peso actualizado del hidden layer:  [[-0.34926055 -0.17741701 -0.3413458 ]
 [-0.40908299 -0.27073592  1.01306048]
 [ 0.17222917 -0.11352756  0.53945246]]
==

HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.18469366]
 [-0.26290368]
 [-0.11511932]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.45395739]
 [ 0.43465005]
 [ 0.47125191]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.08821011]
 [ 0.06237202]
 [-0.13549377]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47796176]
 [ 0.51558795]
 [ 0.46617829]]
ERROR (target - valor de los final outputs)
[[-0.47796176]
 [ 0.48441205]
 [ 0.53382171]]
Peso actualizado del output layer:  [[ 0.05445835 -0.17145324 -0.0815057 ]
 [ 0.58296501 -0.63407625  0.15561108]
 [ 0.30946586 -0.3769513  -0.23795378]]
Peso actualizado del hidden layer:  [[-0.3456394  -0.17424389 -0.35153677]
 [-0.41431738 -0.27338234  1.02557958]
 [ 0.16801194 -0.11543548  0.54798744]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 20
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HI

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 21
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.53300367]
 [ 0.76226135]
 [ 0.43918632]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.3698166 ]
 [ 0.6818445 ]
 [ 0.60806513]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15241671]
 [-0.11162254]
 [-0.27802348]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46196942]
 [ 0.4721233 ]
 [ 0.43093841]]
ERROR (target - valor de los final outputs)
[[ 0.53803058]
 [-0.4721233 ]
 [-0.43093841]]
Peso actualizado del output layer:  [[ 0.04888474 -0.17598646 -0.08304982]
 [ 0.58853033 -0.62756644  0.16220614]
 [ 0.3238577  -0.3768356  -0.23163333]]
Peso actualizado del hidden layer:  [[-0.34196832 -0.1800998  -0.37113416]
 [-0.41949147 -0.26813181  1.04618566]
 [ 0.16390311 -0.11783672  0.55600088]]
==

 [ 0.15989857 -0.11919974  0.56502708]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 22
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.54042793]
 [ 0.77251155]
 [ 0.44582735]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.36808804]
 [ 0.68406394]
 [ 0.60964669]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.15027802]
 [-0.11237123]
 [-0.28060906]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46250104]
 [ 0.47193672]
 [ 0.43030446]]
ERROR (target - valor de los final outputs)
[[ 0.53749896]
 [-0.47193672]
 [-0.43030446]]
Peso actualizado del output layer:  [[ 0.04869656 -0.17542268 -0.07906598]
 [ 0.58857947 -0.62632313  0.16308589]
 [ 0.33233784 -0.38259186 -0.23164458]]
Peso actualizado del hidden layer:  [[-0.33824494 -0.17681379 -0.38197107]
 [-0.42460987 -0.27076832  1.05909671]
 [

Iteración # 23
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.33446678]
 [-0.42967692]
 [ 0.15599439]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.41715418]
 [ 0.39420348]
 [ 0.53891971]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.07919859]
 [ 0.07863612]
 [-0.14370663]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4802107 ]
 [ 0.51964891]
 [ 0.46413504]]
ERROR (target - valor de los final outputs)
[[ 0.5197893 ]
 [-0.51964891]
 [ 0.53586496]]
Peso actualizado del output layer:  [[ 0.05337324 -0.16577876 -0.06700978]
 [ 0.58429878 -0.63315457  0.15676765]
 [ 0.33708435 -0.39566954 -0.2381588 ]]
Peso actualizado del hidden layer:  [[-0.3367828  -0.17343321 -0.393099  ]
 [-0.42894085 -0.27341311  1.07219319]
 [ 0.14993343 -0.12149067  0.57310245]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.07677293]
 [ 0.08072956]
 [-0.14145099]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48081619]
 [ 0.52017144]
 [ 0.4646961 ]]
ERROR (target - valor de los final outputs)
[[ 0.51918381]
 [-0.52017144]
 [ 0.5353039 ]]
Peso actualizado del output layer:  [[ 0.05310761 -0.16535435 -0.06318414]
 [ 0.58432471 -0.63194612  0.1576085 ]
 [ 0.34584144 -0.40162454 -0.23830584]]
Peso actualizado del hidden layer:  [[-0.33285126 -0.16995401 -0.40451812]
 [-0.43403169 -0.27606947  1.0854733 ]
 [ 0.14616293 -0.12329837  0.58164049]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 24
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.73736939]
 [ 0.65144161]
 [ 0.72780342]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.32357965]
 [ 0.65733525]
 [ 0.67432306]]
FI

[[-0.32673599]
 [-0.43967332]
 [ 0.14847233]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.41903502]
 [ 0.39181881]
 [ 0.53705005]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.07444093]
 [ 0.08280727]
 [-0.13918232]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48139836]
 [ 0.52069   ]
 [ 0.46526048]]
ERROR (target - valor de los final outputs)
[[ 0.51860164]
 [-0.52069   ]
 [ 0.53473952]]
Peso actualizado del output layer:  [[ 0.05282029 -0.16500595 -0.05943961]
 [ 0.5843284  -0.63074213  0.1584393 ]
 [ 0.35473014 -0.40767076 -0.23851334]]
Peso actualizado del hidden layer:  [[-0.32885817 -0.16637217 -0.41622868]
 [-0.43908113 -0.27874053  1.09893515]
 [ 0.14248375 -0.12509507  0.59017117]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 25
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[

INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.32277808]
 [-0.44461029]
 [ 0.14484751]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.41999886]
 [ 0.39064298]
 [ 0.5361487 ]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.07219784]
 [ 0.0848712 ]
 [-0.13689474]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48195838]
 [ 0.52120507]
 [ 0.46582966]]
ERROR (target - valor de los final outputs)
[[ 0.51804162]
 [-0.52120507]
 [ 0.53417034]]
Peso actualizado del output layer:  [[ 0.05251347 -0.16473059 -0.05577293]
 [ 0.58431011 -0.6295416   0.1592611 ]
 [ 0.36375418 -0.41380623 -0.23877812]]
Peso actualizado del hidden layer:  [[-0.3248008  -0.16268365 -0.42823095]
 [-0.44409278 -0.28142929  1.11257679]
 [ 0.13889259 -0.12688202  0.59869524]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 26
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
IN

 [ 0.14130915]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42097922]
 [ 0.389477  ]
 [ 0.53526862]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.07003912]
 [ 0.08692319]
 [-0.13458243]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48249737]
 [ 0.52171713]
 [ 0.46640508]]
ERROR (target - valor de los final outputs)
[[ 0.51750263]
 [-0.52171713]
 [ 0.53359492]]
Peso actualizado del output layer:  [[ 0.05218929 -0.16452546 -0.05218099]
 [ 0.58427003 -0.6283436   0.16007482]
 [ 0.37291718 -0.42002901 -0.23909711]]
Peso actualizado del hidden layer:  [[-0.3206764  -0.15888443 -0.44052521]
 [-0.44907007 -0.28413856  1.12639615]
 [ 0.1353863  -0.12866041  0.60721338]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 27
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.76120161]
 [ 0.67732608]
 [

 [ 0.1337623  -0.13207662  0.61917185]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 28
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.89281505]
 [ 0.36256213]
 [ 0.62085752]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.29052924]
 [ 0.58966051]
 [ 0.65041355]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.08428959]
 [-0.08485189]
 [-0.28809911]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47894007]
 [ 0.47879975]
 [ 0.4284693 ]]
ERROR (target - valor de los final outputs)
[[-0.47894007]
 [-0.47879975]
 [-0.4284693 ]]
Peso actualizado del output layer:  [[ 0.0663818  -0.14650593 -0.02642423]
 [ 0.58745875 -0.61958256  0.16884264]
 [ 0.38962664 -0.42380172 -0.23277176]]
Peso actualizado del hidden layer:  [[-0.31050154 -0.15278143 -0.45921433]
 [-0.45921771 -0.28664485  1.14823281]
 [

ERROR (target - valor de los final outputs)
[[-0.46906551]
 [ 0.53946707]
 [-0.41947881]]
Peso actualizado del output layer:  [[ 0.0565107  -0.15958542 -0.0368498 ]
 [ 0.57745806 -0.63186765  0.15542904]
 [ 0.40275385 -0.42978239 -0.23339318]]
Peso actualizado del hidden layer:  [[-0.30626567 -0.14868608 -0.46949692]
 [-0.46402947 -0.28937891  1.16095804]
 [ 0.13118282 -0.13311859  0.63291068]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 30
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.14868608]
 [-0.28937891]
 [-0.13311859]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.46289681]
 [ 0.42815593]
 [ 0.46676941]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.06881211]
 [ 0.08014915]
 [-0.11477848]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48280376]
 [ 0.52002657]
 [ 0.47133684]]
ER

Peso actualizado del output layer:  [[ 0.04609967 -0.1737239  -0.04679007]
 [ 0.58799836 -0.61530942  0.17056412]
 [ 0.41464935 -0.43847179 -0.23441436]]
Peso actualizado del hidden layer:  [[-0.30195314 -0.14250031 -0.49262884]
 [-0.4688173  -0.29523233  1.18340699]
 [ 0.12796102 -0.13570904  0.64123711]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 31
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.30195314]
 [-0.4688173 ]
 [ 0.12796102]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42508009]
 [ 0.38489621]
 [ 0.53194668]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.06216429]
 [ 0.0950444 ]
 [-0.12497324]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48446393]
 [ 0.52374323]
 [ 0.46879729]]
ERROR (target - valor de los final outputs)
[[ 0.51553607]
 [-0.52374323]
 [ 0.53120271]]
Pe

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.28669855]
 [ 0.59630698]
 [ 0.65376361]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.07742597]
 [-0.0858546 ]
 [-0.2990397 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48065317]
 [ 0.47854952]
 [ 0.42579225]]
ERROR (target - valor de los final outputs)
[[-0.48065317]
 [-0.47854952]
 [-0.42579225]]
Peso actualizado del output layer:  [[ 0.0649181  -0.14666874 -0.0131214 ]
 [ 0.58689396 -0.61473271  0.17200889]
 [ 0.42856241 -0.45005328 -0.23485248]]
Peso actualizado del hidden layer:  [[-0.29308631 -0.13563743 -0.51308942]
 [-0.47833153 -0.29776241  1.20636984]
 [ 0.12173258 -0.13836891  0.65388952]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 33
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.46729158]
 [ 0.42540491]
 [ 0.46502911]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.06297388]
 [ 0.08737596]
 [-0.10515819]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48426173]
 [ 0.5218301 ]
 [ 0.47373465]]
ERROR (target - valor de los final outputs)
[[-0.48426173]
 [ 0.4781699 ]
 [ 0.52626535]]
Peso actualizado del output layer:  [[ 0.05068366 -0.16915388 -0.03160885]
 [ 0.58183314 -0.61671913  0.16739937]
 [ 0.4386212  -0.46416083 -0.24227706]]
Peso actualizado del hidden layer:  [[-0.28852606 -0.11896008 -0.52489323]
 [-0.48306267 -0.31180106  1.22000232]
 [ 0.11872128 -0.14091214  0.66675303]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 34
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.64385331]
 [ 0.90820127]
 [ 0.52584089]]
HI

 [ 0.45161716 -0.47272784 -0.2432627 ]]
Peso actualizado del hidden layer:  [[-0.28492099 -0.12402769 -0.54942982]
 [-0.48800124 -0.30684339  1.24307511]
 [ 0.11006174 -0.14269462  0.67519876]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 35
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.83435082]
 [ 0.75507387]
 [ 0.78526049]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.3027259 ]
 [ 0.68028326]
 [ 0.68681276]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.10549702]
 [-0.13997253]
 [-0.34204237]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47365018]
 [ 0.46506389]
 [ 0.41531345]]
ERROR (target - valor de los final outputs)
[[ 0.52634982]
 [ 0.53493611]
 [-0.41531345]]
Peso actualizado del output layer:  [[ 0.05472051 -0.16023142 -0.01901475]
 [ 0.57754599 -0.62374633  0.15945179]
 [

ERROR (target - valor de los final outputs)
[[-0.4820797 ]
 [-0.47819351]
 [-0.42276306]]
Peso actualizado del output layer:  [[ 0.06337461 -0.14771029 -0.00073964]
 [ 0.58598275 -0.60984662  0.17511809]
 [ 0.47004194 -0.47751683 -0.23752816]]
Peso actualizado del hidden layer:  [[-0.27430204 -0.11631707 -0.57167378]
 [-0.49717757 -0.30943587  1.26711158]
 [ 0.11007348 -0.14533136  0.68783184]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 37
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.05182662]
 [ 0.06641872]
 [-0.13046339]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48704624]
 [ 0.51659858]
 [ 0.46743034]]
ERROR (target - valor de los final outputs)
[[-

inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.11111919]
 [-0.31245359]
 [-0.14706899]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.47224875]
 [ 0.42251596]
 [ 0.46329888]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.05791227]
 [ 0.09479853]
 [-0.09421135]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48552598]
 [ 0.5236819 ]
 [ 0.47646457]]
ERROR (target - valor de los final outputs)
[[-0.48552598]
 [ 0.4763181 ]
 [ 0.52353543]]
Peso actualizado del output layer:  [[ 0.04931413 -0.17066541 -0.01962437]
 [ 0.58070457 -0.61173636  0.1705808 ]
 [ 0.48101443 -0.49192214 -0.2450359 ]]
Peso actualizado del hidden layer:  [[-0.26936963 -0.09854592 -0.58501075]
 [-0.50186257 -0.32382521  1.28160201]
 [ 0.10731311 -0.14800159  0.70054935]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 38
in

[[-0.10095611]
 [-0.14482606]
 [-0.36027429]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47478239]
 [ 0.46385664]
 [ 0.41089317]]
ERROR (target - valor de los final outputs)
[[ 0.52521761]
 [ 0.53614336]
 [-0.41089317]]
Peso actualizado del output layer:  [[ 0.05320376 -0.16186294 -0.00720613]
 [ 0.57639939 -0.61885523  0.1625446 ]
 [ 0.5005531  -0.49590152 -0.23926433]]
Peso actualizado del hidden layer:  [[-0.2621677  -0.10322502 -0.60821544]
 [-0.51168007 -0.31908502  1.30066661]
 [ 0.10285087 -0.14965784  0.71297838]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 39
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.36539273]
 [-0.8307651 ]
 [-0.04680697]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.40965477]
 [ 0.30348332]
 [ 0.48830039]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[

inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04775487]
 [ 0.0697666 ]
 [-0.12417098]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48806355]
 [ 0.51743458]
 [ 0.46899708]]
ERROR (target - valor de los final outputs)
[[-0.48806355]
 [-0.51743458]
 [ 0.53100292]]
Peso actualizado del output layer:  [[ 0.05850077 -0.15688733  0.00287681]
 [ 0.58140039 -0.61218277  0.17031558]
 [ 0.51138209 -0.51231807 -0.24740599]]
Peso actualizado del hidden layer:  [[-0.25395792 -0.09458779 -0.63497703]
 [-0.51587979 -0.32176521  1.33027582]
 [ 0.09937431 -0.15228119  0.72171534]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 41
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  

 [ 0.64088623]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12565301]
 [-0.13534847]
 [-0.35919036]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46862801]
 [ 0.46621444]
 [ 0.41115557]]
ERROR (target - valor de los final outputs)
[[ 0.53137199]
 [-0.46621444]
 [-0.41115557]]
Peso actualizado del output layer:  [[ 0.04221055 -0.1780065  -0.01399957]
 [ 0.58486524 -0.60172577  0.17919544]
 [ 0.53236485 -0.51528368 -0.24219744]]
Peso actualizado del hidden layer:  [[-0.24860628 -0.08596038 -0.66016409]
 [-0.52054399 -0.32872827  1.35335448]
 [ 0.096837   -0.15488142  0.73448992]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 42
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.24860628]
 [-0.52054399]
 [ 0.096837  ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.43816657]
 [ 0.37272504]
 [

Iteración # 43
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.32072461]
 [-0.86245401]
 [-0.06383308]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.42049916]
 [ 0.29682689]
 [ 0.48404715]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01638648]
 [ 0.14856439]
 [-0.04994455]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49590347]
 [ 0.53707293]
 [ 0.48751646]]
ERROR (target - valor de los final outputs)
[[ 0.50409653]
 [ 0.46292707]
 [ 0.51248354]]
Peso actualizado del output layer:  [[ 0.05550957 -0.15504598  0.01300205]
 [ 0.57869788 -0.60455444  0.17492185]
 [ 0.54383341 -0.53194877 -0.2494165 ]]
Peso actualizado del hidden layer:  [[-0.226851   -0.06587079 -0.67483232]
 [-0.54358158 -0.34519786  1.36540199]
 [ 0.0917848  -0.15763041  0.74694689]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

Peso actualizado del output layer:  [[ 0.05716304 -0.15946556  0.01373111]
 [ 0.57983078 -0.6072452   0.17333843]
 [ 0.55847124 -0.5418719  -0.25082349]]
Peso actualizado del hidden layer:  [[-0.23186967 -0.07024337 -0.70298894]
 [-0.53452686 -0.33481522  1.39565874]
 [ 0.0895327  -0.15923834  0.75552276]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 45
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.70298894]
 [ 1.39565874]
 [ 0.75552276]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.33114987]
 [ 0.80149409]
 [ 0.68038089]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.11061389]
 [-0.18848538]
 [-0.40807181]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47237469]
 [ 0.45301767]
 [ 0.39937455]]
ERROR (target - valor de los final outputs)
[[-0.47237469]
 [ 0.54698233]
 [-0.39937455]]
Pe

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12359942]
 [-0.14080883]
 [-0.380231  ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46913942]
 [ 0.46485584]
 [ 0.40607118]]
ERROR (target - valor de los final outputs)
[[ 0.53086058]
 [-0.46485584]
 [-0.40607118]]
Peso actualizado del output layer:  [[ 0.04099783 -0.18085663 -0.0033972 ]
 [ 0.5830477  -0.59666132  0.18228889]
 [ 0.58041317 -0.54510291 -0.24569443]]
Peso actualizado del hidden layer:  [[-0.226055   -0.06057033 -0.72989368]
 [-0.53918728 -0.34223954  1.41937108]
 [ 0.08719648 -0.16185846  0.7682601 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 46
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.226055  ]
 [-0.53918728]
 [ 0.08719648]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.44372568]
 [ 0.36837666]
 [ 0.52178532]]
FI

targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.98847164]
 [ 0.51095247]
 [ 0.69900598]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.27121406]
 [ 0.62502973]
 [ 0.66796735]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.06047324]
 [-0.09220115]
 [-0.35157368]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48488629]
 [ 0.47696603]
 [ 0.41300086]]
ERROR (target - valor de los final outputs)
[[-0.48488629]
 [-0.47696603]
 [-0.41300086]]
Peso actualizado del output layer:  [[ 0.05958765 -0.15421642  0.02957569]
 [ 0.58163685 -0.59605366  0.18354493]
 [ 0.5984157  -0.55835249 -0.24684668]]
Peso actualizado del hidden layer:  [[-0.21405773 -0.05016681 -0.75706569]
 [-0.54851095 -0.34509477  1.44601839]
 [ 0.08266546 -0.16446551  0.78081018]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 48
inputs ->  [ 0.  0.  0.]
ta

 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.04311736]
 [-0.34861546]
 [-0.16620953]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.48922233]
 [ 0.41371821]
 [ 0.45854301]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04667619]
 [ 0.11655782]
 [-0.05436333]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48833307]
 [ 0.52910651]
 [ 0.48641251]]
ERROR (target - valor de los final outputs)
[[-0.48833307]
 [ 0.47089349]
 [ 0.51358749]]
Peso actualizado del output layer:  [[ 0.04621724 -0.1783149   0.00978192]
 [ 0.57569682 -0.59766739  0.17921976]
 [ 0.61209729 -0.57332363 -0.25432853]]
Peso actualizado del hidden layer:  [[-0.20787085 -0.0290517  -0.77461997]
 [-0.55317502 -0.36047188  1.46254359]
 [ 0.08046881 -0.16747585  0.793136  ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 49
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [

 [ 0.07705736 -0.16885088  0.80611294]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 50
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.23130765]
 [-0.9197328 ]
 [-0.09179351]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.44242954]
 [ 0.28501234]
 [ 0.47706772]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.00727454]
 [ 0.17073433]
 [-0.00925131]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49818137]
 [ 0.5425802 ]
 [ 0.49768719]]
ERROR (target - valor de los final outputs)
[[ 0.50181863]
 [ 0.4574198 ]
 [ 0.50231281]]
Peso actualizado del output layer:  [[ 0.05330687 -0.1603276   0.03109888]
 [ 0.57493924 -0.59542417  0.18040932]
 [ 0.63169618 -0.58510473 -0.25566662]]
Peso actualizado del hidden layer:  [[-0.18399743 -0.01736021 -0.80262608]
 [-0.57640137 -0.36968918  1.48350808]
 [

inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.83320123]
 [ 1.51473739]
 [ 0.81440344]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.30296861]
 [ 0.81976223]
 [ 0.69304706]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.10812875]
 [-0.20399572]
 [-0.45835821]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47299412]
 [ 0.4491772 ]
 [ 0.38737537]]
ERROR (target - valor de los final outputs)
[[-0.47299412]
 [ 0.5508228 ]
 [-0.38737537]]
Peso actualizado del output layer:  [[ 0.04929041 -0.17146592  0.02524949]
 [ 0.56969542 -0.6049027   0.17211073]
 [ 0.6544795  -0.58904899 -0.25072589]]
Peso actualizado del hidden layer:  [[-0.18853511 -0.02087807 -0.83242075]
 [-0.56717864 -0.35945606  1.51438413]
 [ 0.07414461 -0.17144429  0.8182323 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 52
in

 [ 0.51215568]]
Peso actualizado del output layer:  [[ 0.04347842 -0.17709515  0.02255317]
 [ 0.57550844 -0.5963673   0.18010596]
 [ 0.66874266 -0.60641986 -0.25845579]]
Peso actualizado del hidden layer:  [[-0.18041916 -0.00923466 -0.86301073]
 [-0.57373173 -0.36770167  1.53932658]
 [ 0.06669873 -0.17409996  0.82703844]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 53
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.04342988]
 [ 0.96559485]
 [ 0.89373717]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.26048874]
 [ 0.72424059]
 [ 0.70966079]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.09143759]
 [-0.16413116]
 [-0.4388463 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47715652]
 [ 0.45905908]
 [ 0.39201591]]
ERROR (target - valor de los final outputs)
[[ 0.52284348]
 [ 0.54094092]
 [

Peso actualizado del output layer:  [[ 0.05819484 -0.16055475  0.04668708]
 [ 0.57738779 -0.58697229  0.18884912]
 [ 0.69162835 -0.61302572 -0.2535359 ]]
Peso actualizado del hidden layer:  [[-0.16800724  0.00301087 -0.89326781]
 [-0.58119895 -0.37070161  1.56731998]
 [ 0.06820531 -0.17667768  0.83948   ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 55
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.03742214]
 [ 0.08025538]
 [-0.09519662]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49064556]
 [ 0.52005308]
 [ 0.4762188 ]]
ERROR (target - valor de los final outputs)
[[-0.49064556]
 [-0.52005308]
 [ 0.5237812 ]]
Peso actualizado del output layer:  [[ 0.054986

HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.29172147]
 [ 0.76820541]
 [ 0.66187546]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12093353]
 [-0.15439795]
 [-0.43932853]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46980341]
 [ 0.46147701]
 [ 0.39190098]]
ERROR (target - valor de los final outputs)
[[ 0.53019659]
 [-0.46147701]
 [-0.39190098]]
Peso actualizado del output layer:  [[ 0.03923124 -0.19027816  0.02084167]
 [ 0.57682451 -0.58368671  0.18994698]
 [ 0.71342401 -0.62301691 -0.25510036]]
Peso actualizado del hidden layer:  [[-0.16089528  0.01552896 -0.92426127]
 [-0.58587508 -0.37929     1.5921908 ]
 [ 0.06630861 -0.17934455  0.85205362]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 56
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.16089528]
 [-0.58587508]
 [ 0.06630861]]
HI

ERROR (target - valor de los final outputs)
[[-0.49107892]
 [-0.52054555]
 [ 0.52180331]]
Peso actualizado del output layer:  [[ 0.05479519 -0.17154424  0.04537282]
 [ 0.57209491 -0.59068589  0.18304801]
 [ 0.73180648 -0.64330111 -0.26304251]]
Peso actualizado del hidden layer:  [[-0.14626512  0.02854386 -0.95580536]
 [-0.59522884 -0.38232737  1.62067622]
 [ 0.06263743 -0.18190002  0.86443094]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 58
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.95580536]
 [ 1.62067622]
 [ 0.86443094]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.27771882]
 [ 0.83488837]
 [ 0.70358557]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.1072241 ]
 [-0.217283  ]
 [-0.50709743]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47321963]
 [ 0.44589196]
 [ 0.3758742 ]]
ER

 [ 0.50034264]]
Peso actualizado del output layer:  [[ 0.04542449 -0.1886864   0.03316083]
 [ 0.56857512 -0.58441088  0.18694829]
 [ 0.75053211 -0.65219583 -0.26368155]]
Peso actualizado del hidden layer:  [[-0.13874718  0.05285802 -0.97701233]
 [-0.59990534 -0.39846733  1.63854903]
 [ 0.06086235 -0.18515252  0.87635283]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 59
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.92415431]
 [ 1.2400817 ]
 [ 0.69120031]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.28411218]
 [ 0.77557824]
 [ 0.66623389]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12067194]
 [-0.15834953]
 [-0.45874641]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46986857]
 [ 0.46049513]
 [ 0.38728325]]
ERROR (target - valor de los final outputs)
[[ 0.53013143]
 [-0.46049513]
 [

Peso actualizado del hidden layer:  [[-0.12857402  0.05109866 -1.00967895]
 [-0.60709758 -0.39530541  1.66377117]
 [ 0.05379394 -0.18631081  0.88519011]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 60
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.13825296]
 [ 1.05667359]
 [ 0.93898405]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.24264126]
 [ 0.74205435]
 [ 0.71889439]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.08932555]
 [-0.17414344]
 [-0.48604695]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47768345]
 [ 0.45657383]
 [ 0.38082525]]
ERROR (target - valor de los final outputs)
[[ 0.52231655]
 [ 0.54342617]
 [-0.38082525]]
Peso actualizado del output layer:  [[ 0.04885504 -0.18007222  0.04512982]
 [ 0.56416936 -0.59202034  0.17843659]
 [ 0.77505308 -0.6579038  -0.25860047]]
Pe

Iteración # 62
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.04288768]
 [ 1.6928291 ]
 [ 0.89746428]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.2605932 ]
 [ 0.84459585]
 [ 0.71042813]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.10711932]
 [-0.22592903]
 [-0.54238601]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47324575]
 [ 0.44375678]
 [ 0.36763271]]
ERROR (target - valor de los final outputs)
[[-0.47324575]
 [ 0.55624322]
 [-0.36763271]]
Peso actualizado del output layer:  [[ 0.04881071 -0.18233471  0.0480838 ]
 [ 0.56236633 -0.59197146  0.17946752]
 [ 0.79781001 -0.6692693  -0.26044548]]
Peso actualizado del hidden layer:  [[-0.11538989  0.06507906 -1.04295682]
 [-0.61392501 -0.39836002  1.69286919]
 [ 0.05577658 -0.18882389  0.90101954]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

targets ->  [ 1.  0.  0.]
INPUTS
[[ 0.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.97483284]
 [ 1.29636434]
 [ 0.71705913]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.27391826]
 [ 0.78522247]
 [ 0.67195909]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12062964]
 [-0.16347717]
 [-0.48579212]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46987911]
 [ 0.45922148]
 [ 0.38088534]]
ERROR (target - valor de los final outputs)
[[ 0.53012089]
 [-0.45922148]
 [-0.38088534]]
Peso actualizado del output layer:  [[ 0.03953668 -0.19846835  0.03628546]
 [ 0.57099186 -0.57440971  0.19518622]
 [ 0.81734523 -0.67968864 -0.26187772]]
Peso actualizado del hidden layer:  [[-0.1073404   0.07961856 -1.0764311 ]
 [-0.61859226 -0.40768834  1.7181332 ]
 [ 0.05416069 -0.19149723  0.90985017]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 63
inputs ->  [ 1.  0.  0.]
ta

Iteración # 64
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.00619139]
 [-1.04093988]
 [-0.14141608]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.49845216]
 [ 0.26096868]
 [ 0.46470478]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.00975448]
 [ 0.21934675]
 [ 0.10900255]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.5024386 ]
 [ 0.55461788]
 [ 0.52722369]]
ERROR (target - valor de los final outputs)
[[ 0.4975614 ]
 [ 0.44538212]
 [ 0.47277631]]
Peso actualizado del output layer:  [[ 0.05231936 -0.17512068  0.06321605]
 [ 0.56372489 -0.57657613  0.19114325]
 [ 0.83432266 -0.69717194 -0.2688316 ]]
Peso actualizado del hidden layer:  [[-0.07886202  0.10624796 -1.09884383]
 [-0.64205249 -0.42486758  1.73341607]
 [ 0.05153798 -0.19347702  0.92252433]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

 [-0.39425811]]
Peso actualizado del output layer:  [[ 0.05873174 -0.17313188  0.07111313]
 [ 0.56825336 -0.57236797  0.19697875]
 [ 0.85599359 -0.70233872 -0.2643411 ]]
Peso actualizado del hidden layer:  [[-0.08242738  0.10429496 -1.13396735]
 [-0.63256327 -0.41490559  1.76589286]
 [ 0.04955044 -0.19566905  0.93018038]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 66
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.03140674]
 [ 0.0869294 ]
 [-0.06289447]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49214896]
 [ 0.52171867]
 [ 0.48428156]]
ERROR (target - valor de los final outputs)
[[-0.49214896]
 [-0.52171867]
 [ 0.51571844]]
Peso actualizado del output lay

 [ 0.74268607]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.26370055]
 [ 0.79462218]
 [ 0.67758295]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12089547]
 [-0.16842128]
 [-0.51413929]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46981289]
 [ 0.45799393]
 [ 0.37422368]]
ERROR (target - valor de los final outputs)
[[ 0.53018711]
 [-0.45799393]
 [-0.37422368]]
Peso actualizado del output layer:  [[ 0.04041877 -0.2036373   0.04465991]
 [ 0.56711126 -0.5690767   0.19810437]
 [ 0.88046565 -0.71259654 -0.26575869]]
Peso actualizado del hidden layer:  [[-0.0738768   0.11992329 -1.16879492]
 [-0.63720669 -0.42460244  1.79130489]
 [ 0.04809288 -0.19832968  0.94243143]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 67
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.0738768 ]
 [-0.63720669]
 [

 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.0690233 ]
 [-1.07666712]
 [-0.15401398]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.51724898]
 [ 0.25413725]
 [ 0.46157243]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.0147712 ]
 [ 0.23389955]
 [ 0.15332724]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.50369273]
 [ 0.55820974]
 [ 0.53825689]]
ERROR (target - valor de los final outputs)
[[ 0.49630727]
 [ 0.44179026]
 [ 0.46174311]]
Peso actualizado del output layer:  [[ 0.05316538 -0.18017897  0.0716283 ]
 [ 0.55960428 -0.57112254  0.19409373]
 [ 0.89839114 -0.73008121 -0.27259823]]
Peso actualizado del hidden layer:  [[-0.04416092  0.14756526 -1.19245189]
 [-0.66064504 -0.44175751  1.80694889]
 [ 0.04589087 -0.2001321   0.95507195]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 68
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [

Iteración # 70
inputs ->  [ 0.  1.  0.]
targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.14591028]
 [-0.4318434 ]
 [-0.20239314]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.53641299]
 [ 0.39368623]
 [ 0.44957373]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.0287837 ]
 [ 0.16271329]
 [ 0.07972475]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49280457]
 [ 0.54058881]
 [ 0.51992064]]
ERROR (target - valor de los final outputs)
[[-0.49280457]
 [ 0.45941119]
 [ 0.48007936]]
Peso actualizado del output layer:  [[ 0.04805545 -0.20287275  0.05629097]
 [ 0.55782513 -0.56956792  0.19511748]
 [ 0.92300918 -0.74216232 -0.27406023]]
Peso actualizado del hidden layer:  [[-0.04753209  0.16271336 -1.22938007]
 [-0.65108133 -0.44420759  1.83986787]
 [ 0.04395896 -0.20411723  0.96586644]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.2988587 ]
 [ 1.20591171]
 [ 1.01210588]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.21435716]
 [ 0.76957477]
 [ 0.73343207]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.08841671]
 [-0.18914124]
 [-0.56993387]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47791021]
 [ 0.45285515]
 [ 0.36125208]]
ERROR (target - valor de los final outputs)
[[ 0.52208979]
 [ 0.54714485]
 [-0.36125208]]
Peso actualizado del output layer:  [[ 0.0513844  -0.19420253  0.06820269]
 [ 0.55334936 -0.5774677   0.18631438]
 [ 0.94981047 -0.74848298 -0.26930773]]
Peso actualizado del hidden layer:  [[-0.03439693  0.16253651 -1.26491754]
 [-0.6617148  -0.44185936  1.86241449]
 [ 0.0420718  -0.20502704  0.97921665]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 71
inputs ->  [ 1.  1.  0.]
ta

 [ 0.04018614 -0.20732918  0.98651726]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 73
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.02778053]
 [ 0.09030809]
 [-0.03786352]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49305531]
 [ 0.52256169]
 [ 0.49053525]]
ERROR (target - valor de los final outputs)
[[-0.49305531]
 [-0.52256169]
 [ 0.50946475]]
Peso actualizado del output layer:  [[ 0.05820308 -0.19074348  0.07697934]
 [ 0.5579427  -0.57102388  0.19369736]
 [ 0.96854195 -0.76664367 -0.27762533]]
Peso actualizado del hidden layer:  [[-0.02023345  0.17847019 -1.30200728]
 [-0.66484942 -0.44472481  1.89514072]
 [ 0.04018614 -0.20732918  0.98651726]]
=======

ERROR (target - valor de los final outputs)
[[ 0.53046266]
 [-0.45596761]
 [-0.36195921]]
Peso actualizado del output layer:  [[ 0.04332947 -0.21342283  0.05865238]
 [ 0.55939558 -0.55975559  0.20303368]
 [ 0.99669186 -0.77071222 -0.27257479]]
Peso actualizado del hidden layer:  [[-0.01094373  0.19576655 -1.33869148]
 [-0.66940994 -0.4549446   1.92050593]
 [ 0.03900961 -0.20993339  0.99848893]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 74
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-0.01094373]
 [-0.66940994]
 [ 0.03900961]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.4972641 ]
 [ 0.33862898]
 [ 0.50975117]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01095774]
 [ 0.18366582]
 [ 0.08944423]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49726059]
 [ 0.54578781]
 [ 0.52234616]]
ER

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.50602056]
 [ 0.56446901]
 [ 0.56037065]]
ERROR (target - valor de los final outputs)
[[ 0.49397944]
 [ 0.43553099]
 [ 0.43962935]]
Peso actualizado del output layer:  [[ 0.05604269 -0.18976044  0.08571099]
 [ 0.55146014 -0.561602    0.19906886]
 [ 1.01607889 -0.7880801  -0.27919752]]
Peso actualizado del hidden layer:  [[ 0.02062993  0.22471452 -1.36422404]
 [-0.6926848  -0.47189853  1.9365794 ]
 [ 0.03754438 -0.21138645  1.01101919]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 75
inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.11887959]
 [ 0.77199607]
 [ 0.83717712]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.24621917]
 [ 0.68395253]
 [ 0.69787035]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04851239]
 [-0.10276175]
 [-0.47695544]]
FI

targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.22331525]
 [-0.46202822]
 [-0.21373008]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.55559795]
 [ 0.38650478]
 [ 0.44676996]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.02222685]
 [ 0.17814507]
 [ 0.1442756 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49444352]
 [ 0.54441886]
 [ 0.53600646]]
ERROR (target - valor de los final outputs)
[[-0.49444352]
 [ 0.45558114]
 [ 0.46399354]]
Peso actualizado del output layer:  [[ 0.05199376 -0.21309827  0.06994432]
 [ 0.54946981 -0.56015208  0.20001844]
 [ 1.04201765 -0.80016551 -0.28068019]]
Peso actualizado del hidden layer:  [[ 0.01742144  0.2407991  -1.40333056]
 [-0.68298998 -0.47438452  1.96974297]
 [ 0.03572625 -0.21555152  1.02125762]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 77
inputs ->  [ 0.  1.  1.]
ta

 [ 1.0639796  -0.81068229 -0.28213478]]
Peso actualizado del hidden layer:  [[ 0.03255152  0.24138081 -1.43977522]
 [-0.69139786 -0.47247039  1.99454462]
 [ 0.02964462 -0.21628192  1.02989827]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 78
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.40722369]
 [ 1.30314675]
 [ 1.05954289]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.19667232]
 [ 0.7863641 ]
 [ 0.74260318]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.08905602]
 [-0.19781786]
 [-0.62910233]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4777507 ]
 [ 0.45070618]
 [ 0.34771411]]
ERROR (target - valor de los final outputs)
[[ 0.5222493 ]
 [ 0.54929382]
 [-0.34771411]]
Peso actualizado del output layer:  [[ 0.05526954 -0.20436978  0.08185132]
 [ 0.54495454 -0.56824432  0.19101937]
 [

 [ 0.70234731]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04792376]
 [-0.10396949]
 [-0.49692831]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.48802135]
 [ 0.47403102]
 [ 0.3782628 ]]
ERROR (target - valor de los final outputs)
[[-0.48802135]
 [-0.47403102]
 [-0.3782628 ]]
Peso actualizado del output layer:  [[ 0.06555812 -0.19270426  0.09902968]
 [ 0.55238579 -0.55370456  0.20660257]
 [ 1.09193369 -0.81881364 -0.27828545]]
Peso actualizado del hidden layer:  [[ 0.04640814  0.25774356 -1.47918168]
 [-0.69639653 -0.47502863  2.02494218]
 [ 0.03281697 -0.21837006  1.04148243]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 80
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cr

targets ->  [ 0.  1.  1.]
INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.26932627]
 [-0.47935572]
 [-0.21988241]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5669275 ]
 [ 0.38240427]
 [ 0.44524981]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01816386]
 [ 0.18661407]
 [ 0.18535436]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49545916]
 [ 0.5465186 ]
 [ 0.54620638]]
ERROR (target - valor de los final outputs)
[[-0.49545916]
 [ 0.4534814 ]
 [ 0.45379362]]
Peso actualizado del output layer:  [[ 0.05505514 -0.21929254  0.07744476]
 [ 0.54421936 -0.55482648  0.20269334]
 [ 1.11247396 -0.83329855 -0.28451622]]
Peso actualizado del hidden layer:  [[ 0.05617991  0.28711055 -1.50630151]
 [-0.70082248 -0.49166257  2.04391786]
 [ 0.03193141 -0.22174888  1.05225364]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 81
inputs ->  [ 0.  1.  1.]
ta

Peso actualizado del hidden layer:  [[ 0.07125346  0.28800411 -1.54407361]
 [-0.71157975 -0.48996361  2.06623229]
 [ 0.03077161 -0.22236803  1.0654928 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 82
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.35925758]
 [-1.20154336]
 [-0.19159642]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5888607 ]
 [ 0.23120078]
 [ 0.45224689]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.03430463]
 [ 0.28378452]
 [ 0.34601397]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.50857532]
 [ 0.57047381]
 [ 0.58565064]]
ERROR (target - valor de los final outputs)
[[ 0.49142468]
 [ 0.42952619]
 [ 0.41434936]]
Peso actualizado del output layer:  [[ 0.06072959 -0.20015607  0.09910429]
 [ 0.5422314  -0.55219228  0.20376712]
 [ 1.13937125 -0.84609558 -0.28590365]]
Pe

 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.0218135 ]
 [ 0.0941615 ]
 [ 0.00718744]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49454684]
 [ 0.523523  ]
 [ 0.50179685]]
ERROR (target - valor de los final outputs)
[[-0.49454684]
 [-0.523523  ]
 [ 0.49820315]]
Peso actualizado del output layer:  [[ 0.06590897 -0.20742685  0.09789087]
 [ 0.54423946 -0.55672495  0.20080849]
 [ 1.16113091 -0.85818955 -0.28856648]]
Peso actualizado del hidden layer:  [[ 0.08573525  0.30427505 -1.58352277]
 [-0.71396026 -0.49229148  2.09883899]
 [ 0.02953043 -0.22430742  1.07219849]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 84
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de i

[[-1.2772467 ]
 [ 1.60894868]
 [ 0.85508295]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.21801926]
 [ 0.83326537]
 [ 0.70163232]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12516196]
 [-0.18804824]
 [-0.65779658]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46875029]
 [ 0.45312599]
 [ 0.34123475]]
ERROR (target - valor de los final outputs)
[[ 0.53124971]
 [-0.45312599]
 [-0.34123475]]
Peso actualizado del output layer:  [[ 0.05150342 -0.23041013  0.07924675]
 [ 0.5451272  -0.54532916  0.21023467]
 [ 1.19055345 -0.86214844 -0.28356978]]
Peso actualizado del hidden layer:  [[ 0.09564582  0.32330491 -1.62189343]
 [-0.71829049 -0.50298749  2.12357586]
 [ 0.02881602 -0.22673515  1.08364362]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 85
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[

Iteración # 86
inputs ->  [ 1.  0.  1.]
targets ->  [ 1.  1.  0.]
INPUTS
[[ 1.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.53596409]
 [ 1.41491162]
 [ 1.11440245]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.17712274]
 [ 0.80453948]
 [ 0.75294895]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.09075709]
 [-0.20660949]
 [-0.70169782]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47732629]
 [ 0.44853059]
 [ 0.33143591]]
ERROR (target - valor de los final outputs)
[[ 0.52267371]
 [ 0.55146941]
 [-0.33143591]]
Peso actualizado del output layer:  [[ 0.06187733 -0.21690784  0.09667847]
 [ 0.53411794 -0.5578708   0.19604936]
 [ 1.21284981 -0.87311552 -0.28430241]]
Peso actualizado del hidden layer:  [[ 0.11125883  0.33509027 -1.64941182]
 [-0.72905239 -0.50730107  2.13982381]
 [ 0.02791898 -0.22815007  1.09589125]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49512346]
 [ 0.52376652]
 [ 0.50620402]]
ERROR (target - valor de los final outputs)
[[-0.49512346]
 [-0.52376652]
 [ 0.49379598]]
Peso actualizado del output layer:  [[ 0.06977215 -0.21392573  0.10514   ]
 [ 0.53867417 -0.55162259  0.20322399]
 [ 1.23349912 -0.89117935 -0.29268505]]
Peso actualizado del hidden layer:  [[ 0.12546609  0.35102997 -1.68943519]
 [-0.73112585 -0.50936868  2.17223687]
 [ 0.02693314 -0.22992396  1.10237398]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 88
inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.68943519]
 [ 2.17223687]
 [ 1.10237398]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.15585013]
 [ 0.89772852]
 [ 0.75070465]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.11340987]
 [-0.2704798 ]
 [-0.81638101]]
FI

FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.12670152]
 [-0.19175377]
 [-0.69322569]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.46836693]
 [ 0.45220791]
 [ 0.33331589]]
ERROR (target - valor de los final outputs)
[[ 0.53163307]
 [-0.45220791]
 [-0.33331589]]
Peso actualizado del output layer:  [[ 0.05550075 -0.23699895  0.08639425]
 [ 0.53939173 -0.54019833  0.212679  ]
 [ 1.26311988 -0.89504381 -0.28772699]]
Peso actualizado del hidden layer:  [[ 0.13541542  0.37038852 -1.72800552]
 [-0.735351   -0.52013658  2.19659885]
 [ 0.02639283 -0.23226506  1.11360894]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 89
inputs ->  [ 1.  0.  0.]
targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.13541542]
 [-0.735351  ]
 [ 0.02639283]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.53380222]
 [ 0.32402159]
 [ 0.50659782]]
FI

inputs ->  [ 1.  1.  1.]
targets ->  [ 0.  0.  0.]
INPUTS
[[ 1.]
 [ 1.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.18741729]
 [ 0.91894947]
 [ 0.91944819]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.23372117]
 [ 0.714828  ]
 [ 0.71492966]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.04732121]
 [-0.10748429]
 [-0.55590556]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.4881719 ]
 [ 0.47315477]
 [ 0.36449536]]
ERROR (target - valor de los final outputs)
[[-0.4881719 ]
 [-0.47315477]
 [-0.36449536]]
Peso actualizado del output layer:  [[ 0.07585301 -0.21021193  0.11919454]
 [ 0.53708822 -0.5394106   0.21340928]
 [ 1.29015593 -0.90966685 -0.2898005 ]]
Peso actualizado del hidden layer:  [[ 0.15529291  0.38593625 -1.76955606]
 [-0.74371922 -0.52199496  2.22682453]
 [ 0.025444   -0.23390546  1.12463662]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 91
in

INPUTS
[[ 0.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.3975022 ]
 [-0.52616198]
 [-0.23518625]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.59808739]
 [ 0.37141249]
 [ 0.44147296]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.00565751]
 [ 0.2077311 ]
 [ 0.31113158]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49858563]
 [ 0.55174683]
 [ 0.57716144]]
ERROR (target - valor de los final outputs)
[[-0.49858563]
 [ 0.44825317]
 [ 0.42283856]]
Peso actualizado del output layer:  [[ 0.06627094 -0.23743571  0.09715944]
 [ 0.52830462 -0.54051944  0.20955856]
 [ 1.31168498 -0.92331079 -0.29546885]]
Peso actualizado del hidden layer:  [[ 0.16521002  0.41573262 -1.79783959]
 [-0.74786181 -0.53816954  2.24547725]
 [ 0.0250357  -0.2371451   1.13474004]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 92
inputs ->  [ 0.  1.  1.]
targets ->  [ 1.  0.  0.]
IN

Iteración # 93
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.59856274]
 [-1.29554388]
 [-0.2128361 ]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.64532742]
 [ 0.21491593]
 [ 0.44699093]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.05250893]
 [ 0.31794907]
 [ 0.5304719 ]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.51312422]
 [ 0.57882434]
 [ 0.62959317]]
ERROR (target - valor de los final outputs)
[[ 0.48687578]
 [ 0.42117566]
 [ 0.37040683]]
Peso actualizado del output layer:  [[ 0.07145841 -0.21786241  0.11905601]
 [ 0.52595911 -0.53781563  0.21055993]
 [ 1.33936279 -0.93584888 -0.29693399]]
Peso actualizado del hidden layer:  [[ 0.19874513  0.43426045 -1.83622493]
 [-0.77005077 -0.54841407  2.26693356]
 [ 0.02550207 -0.23652568  1.1477241 ]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
It

inputs ->  [ 0.  0.  1.]
targets ->  [ 0.  1.  0.]
INPUTS
[[ 0.]
 [ 0.]
 [ 1.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[-1.87683747]
 [ 2.29883042]
 [ 1.15381265]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.13275255]
 [ 0.90878013]
 [ 0.76020662]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.11672977]
 [-0.27744217]
 [-0.89804328]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.47085065]
 [ 0.43108097]
 [ 0.28945277]]
ERROR (target - valor de los final outputs)
[[-0.47085065]
 [ 0.56891903]
 [-0.28945277]]
Peso actualizado del output layer:  [[ 0.071506   -0.23196645  0.11126465]
 [ 0.52181341 -0.54940647  0.20070261]
 [ 1.36736916 -0.94194589 -0.294056  ]]
Peso actualizado del hidden layer:  [[ 0.19481287  0.43190012 -1.87836394]
 [-0.76012175 -0.5385218   2.29940493]
 [ 0.02407628 -0.23888425  1.15649071]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 95
in

targets ->  [ 1.  0.  1.]
INPUTS
[[ 1.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.20461513]
 [-0.76415231]
 [ 0.02384515]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.55097605]
 [ 0.31774543]
 [ 0.50596101]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.01559396]
 [ 0.22393419]
 [ 0.30947719]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.50389841]
 [ 0.55575077]
 [ 0.57675764]]
ERROR (target - valor de los final outputs)
[[ 0.49610159]
 [-0.55575077]
 [ 0.42324236]]
Peso actualizado del output layer:  [[ 0.06614502 -0.23765841  0.10804095]
 [ 0.52668852 -0.54094271  0.20875819]
 [ 1.3895994  -0.9575682  -0.30021262]]
Peso actualizado del hidden layer:  [[ 0.21273595  0.45148223 -1.91523082]
 [-0.76897697 -0.54930241  2.32238434]
 [ 0.0191088  -0.24105395  1.16466471]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 96
inputs ->  [ 1.  0.  1.]
ta

 [ 1.41353968 -0.96223358 -0.29608854]]
Peso actualizado del hidden layer:  [[ 0.22119635  0.46282852 -1.94341586]
 [-0.7748434  -0.55336319  2.33826965]
 [ 0.02366397 -0.24221146  1.17653216]]
============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 97
inputs ->  [ 1.  1.  0.]
targets ->  [ 1.  1.  1.]
INPUTS
[[ 1.]
 [ 1.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.68402487]
 [-1.32820659]
 [-0.21854748]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.66463641]
 [ 0.20945617]
 [ 0.44557956]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[ 0.05976832]
 [ 0.32863075]
 [ 0.60196469]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.51493763]
 [ 0.58142618]
 [ 0.64610567]]
ERROR (target - valor de los final outputs)
[[ 0.48506237]
 [ 0.41857382]
 [ 0.35389433]]
Peso actualizado del output layer:  [[ 0.07621704 -0.22465186  0.12605251]
 [ 0.51964347 -0.53275251  0.21285779]
 [

============= FINAL DE FASE DE ENTRENAMIENTO ==============
Iteración # 99
inputs ->  [ 0.  0.  0.]
targets ->  [ 0.  0.  1.]
INPUTS
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN INPUTS (multiplicación cruz de inputs directos con peso wih)
[[ 0.]
 [ 0.]
 [ 0.]]
HIDDEN OUTPUTS (después de aplicar la función sigmoide)
[[ 0.5]
 [ 0.5]
 [ 0.5]]
FINAL INPUTS (multiplicación cruz de hidden outputs con peso who)
[[-0.01280612]
 [ 0.09680682]
 [ 0.07500044]]
FINAL OUTPUTS (después de aplicar función sigmoide a los final inputs)
[[ 0.49679851]
 [ 0.52418282]
 [ 0.51874132]]
ERROR (target - valor de los final outputs)
[[-0.49679851]
 [-0.52418282]
 [ 0.48125868]]
Peso actualizado del output layer:  [[ 0.08281203 -0.23276486  0.1243406 ]
 [ 0.52218598 -0.53798909  0.20941675]
 [ 1.43428876 -0.9797846  -0.30450329]]
Peso actualizado del hidden layer:  [[ 0.23376617  0.47685347 -1.98412325]
 [-0.77607658 -0.55463637  2.36977997]
 [ 0.02341821 -0.24346696  1.18239443]]
============= FINAL DE FASE DE ENTRENAMIENTO ==

In [30]:
# load the mnist test data CSV file into a list
test_data_file = open("mnist_dataset/contador.csv", 'r')
test_data_list = test_data_file.readlines()
test_data_file.close()

In [38]:
# test the neural network

# scorecard for how well the network performs, initially empty
scorecard = []

# go through all the records in the test data set
for record in test_data_list:
    # split the record by the ',' commas
    all_values = record.split(',')
    # correct answer is first value
    correct_label = int(all_values[0])
    # scale and shift the inputs
    # inputs = (numpy.asfarray(all_values[1:]) / 255.0 * 0.99) + 0.01
    inputs = (numpy.asfarray(all_values[0:3]) / 1.0) + 0.00
    # query the network
    outputs = n.query(inputs)
    print("Outputs -> ", outputs)
    # the index of the highest value corresponds to the label
    label = numpy.argmax(outputs)
    # append correct or incorrect to list
    if (label == correct_label):
        # network's answer matches correct answer, add 1 to scorecard
        scorecard.append(1)
    else:
        # network's answer doesn't match correct answer, add 0 to scorecard
        scorecard.append(0)
        pass
    
    pass

Outputs ->  [[ 0.43989384]
 [ 0.51993662]
 [ 0.65679279]]
Outputs ->  [[ 0.3811616 ]
 [ 0.47311188]
 [ 0.15361066]]
Outputs ->  [[ 0.30698364]
 [ 0.53523162]
 [ 0.80216717]]
Outputs ->  [[ 0.35260061]
 [ 0.47398271]
 [ 0.16097631]]
Outputs ->  [[ 0.74257478]
 [ 0.54444246]
 [ 0.82155565]]
Outputs ->  [[ 0.5920998 ]
 [ 0.48284944]
 [ 0.20954849]]
Outputs ->  [[ 0.68180777]
 [ 0.55284104]
 [ 0.87408349]]
Outputs ->  [[ 0.47099956]
 [ 0.48239088]
 [ 0.20872126]]


In [32]:
# calculate the performance score, the fraction of correct answers
scorecard_array = numpy.asarray(scorecard)
print ("performance = ", scorecard_array.sum() / scorecard_array.size)

performance =  0.0
